# <b>Final Project - Job Application Helper (Resume Screening / Recommending Job / Comparing Job Description and Resume)</b>

#### Importing the necessary libraries

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Importing the dataset into dataframe and displaying the first 5 rows in it.

In [13]:
df1 = pd.read_csv('ResumeDataSet.csv')
df1.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [14]:
# Rename the column
df1.rename(columns={'Label': 'Category'}, inplace=True)
df1.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

# <b>Data Exploration</b>

- Checking if the dataset has any null values or not

In [15]:
df1.isnull().sum()

Category    0
Resume      0
dtype: int64

In [16]:
df1.dropna(inplace=True)
df1.isnull().sum()

Category    0
Resume      0
dtype: int64

- Finding basic information about the dataset
    - It has 29033 rows and 2 columns
    - Both the columns contains data of Object datatype i.e. string

In [17]:
print(df1.shape)
print(df1.info())

(962, 2)
<class 'pandas.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  962 non-null    str
 1   Resume    962 non-null    str
dtypes: str(2)
memory usage: 15.2 KB
None

- Looking at the Unique Categories

In [18]:
unique_categories = df1['Category'].unique()
print(unique_categories)

<StringArray>
[             'Data Science',                        'HR',
                  'Advocate',                      'Arts',
             'Web Designing',       'Mechanical Engineer',
                     'Sales',        'Health and fitness',
            'Civil Engineer',            'Java Developer',
          'Business Analyst',             'SAP Developer',
        'Automation Testing',    'Electrical Engineering',
        'Operations Manager',          'Python Developer',
           'DevOps Engineer', 'Network Security Engineer',
                       'PMO',                  'Database',
                    'Hadoop',             'ETL Developer',
          'DotNet Developer',                'Blockchain',
                   'Testing']
Length: 25, dtype: str

- Exploring Categories - getting value counts of each category.

In [19]:
df1['Category'].value_counts()

Category
Java Developer               84
Testing                      70
DevOps Engineer              55
Python Developer             48
Web Designing                45
HR                           44
Hadoop                       42
Data Science                 40
Mechanical Engineer          40
Sales                        40
Operations Manager           40
ETL Developer                40
Blockchain                   40
Arts                         36
Database                     33
Health and fitness           30
Electrical Engineering       30
PMO                          30
Business Analyst             28
DotNet Developer             28
Automation Testing           26
Network Security Engineer    25
Civil Engineer               24
SAP Developer                24
Advocate                     20
Name: count, dtype: int64

In [20]:
temp_df = df1

# <b>Data Processing</b>

In [21]:
# Preprocessing libraries
import re
from sklearn.preprocessing import LabelEncoder
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer 
import string
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\asrit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\asrit\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

### Cleaning Data:                                     
1 Removing (URLs, hashtags, mentions, special letters, punctuations)

2 Tokenizing the cleaned text

3 Removing Stop Words

4 Performing Lemmatization on final text    

- The resumeKeywords function removes URLs, hashtags, mentions, special characters, non-ASCII characters, multiple spaces, and stop words from the input text while also performing tokenization, lowercasing, and lemmatization to provide cleaned and processed text as output.

- <b>Tokenization:</b> Tokenization is the process of breaking a text into individual words or tokens. In this step, the text is split into its constituent words, which makes it easier to analyze and process. For example, the sentence "I love coding" would be tokenized into three tokens: "I," "love," and "coding."

- <b> StopWords: </b> Stopwords are common words that are typically removed from text during natural language processing to improve text analysis and reduce noise in the data.Examples of common stopwords in English include "the," "and," "in," "is," "of," "it," "to," and many others. Removing stopwords from text helps reduce the dimensionality of the data and focuses the analysis on more meaningful words

- <b>Lemmatization:</b> Lemmatization is the process of reducing words to their base or root form. This step is essential for text analysis because it reduces different forms of a word to a common base form. For example, the words "running" and "ran" would both be lemmatized to "run." This simplifies the text and ensures that similar words are treated as the same, which is crucial for accurate analysis and modeling.

In [22]:

def resumeKeywords(txt):   # sourcery skip: avoid-builtin-shadow, list-comprehension
    cleanText = re.sub('http\S+\s', ' ', txt) # Removing URLs
    cleanText = re.sub('#\S+\s', ' ', cleanText) # Removing hashtags
    cleanText = re.sub('@\S+', '  ', cleanText)  # Removing mentions
    cleanText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', cleanText) # Removing punctuations
    cleanText = re.sub(r'[^\x00-\x7f]', ' ', cleanText) # Removing non-ASCII characters
    cleanText = re.sub('\s+', ' ', cleanText) # Replace multiple spaces with a single space
    cleanText = cleanText.strip() # Removing leading and trailing whitespaces
    
    #------------Tokenizing Cleaned Text--------------------------------------------------------
    # Tokenizing our cleaned text
    tokenizer = nltk.tokenize.RegexpTokenizer('\w+')
    tokens = tokenizer.tokenize(cleanText)
    # Now lower everything and storing it in new variable words
    words = []
    for word in tokens:
        words.append(word.lower())
    #--------------------------------------------------------------------------------------------

    #-------------Removing Stop Words------------------------------------------------------------
    stopwords = nltk.corpus.stopwords.words('english')
    words_new = []
    for word in words:
        if word not in stopwords:
            words_new.append(word)
    #--------------------------------------------------------------------------------------------
    #-----------Performing Lemmatization---------------------------------------------------------
    wn = WordNetLemmatizer() 
    lemm_text = [wn.lemmatize(word) for word in words_new]
    #--------------------------------------------------------------------------------------------
    #----------Converting List into String-------------------------------------------------------
    processed_text = ' '.join(lemm_text)
    
    return processed_text

- Testing the above custom function to remove certain details from Resume

In [23]:
resumeKeywords(" https://www.github.com Software Engineer with 2 years of experience in Data Structures and Algorithms Agile Scrum, SDLC, C++, Java MVC, JavaScript, Web Development, Python " +
               "Data Science, Machine Learning / AI, and Mainframe technologies Programming Languages: 	C/C++, Java, Python, SQL, JCL, Cobol, DB2" + 
               "Frameworks: %#####	Java Spring, Spring boot, React, Angular, NodeJs" +
               "Tools: 	GIT, Visual Studio Code, Sublime, Spyder, Jupyter Notebook, Bluezone, Netbeans, Jira, Confluence, Kanban, CI/CD (Jenkins, GitLab, Azure-Devops), AWS," + 
               "Data-Bricks Libraries: 	NumPy, Pandas, Matplotlib, nltk, Scikit learn, TensorFlow, Keras Other: 	Problem-Solving, Quick Learner, Time-Management")

'software engineer 2 year experience data structure algorithm agile scrum sdlc c java mvc javascript web development python data science machine learning ai mainframe technology programming language c c java python sql jcl cobol db2frameworks java spring spring boot react angular nodejstools git visual studio code sublime spyder jupyter notebook bluezone netbeans jira confluence kanban ci cd jenkins gitlab azure devops aws data brick library numpy panda matplotlib nltk scikit learn tensorflow kera problem solving quick learner time management'

#### Applying above created Custom Function to process the data and creating new column "Processed_Resume"

In [24]:
df1['Processed_Resume'] = df1['Resume'].apply(lambda x: resumeKeywords(x))
df1.head()

,Category,Resume,Processed_Resume
0,Data Science,Skills * Programming Languages: Python (pandas...,skill programming language python panda numpy ...
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,education detail may 2013 may 2017 b e uit rgp...
2,Data Science,"Areas of Interest Deep Learning, Control Syste...",area interest deep learning control system des...
3,Data Science,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,skill r python sap hana tableau sap hana sql s...
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",education detail mca ymcaust faridabad haryana...

#### Generating WordCloud from the cleaned text

In [25]:
!pip install wordcloud
from wordcloud import WordCloud

Collecting wordcloud
  Using cached wordcloud-1.9.6-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.19.3 in C:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages (from wordcloud) (2.4.6)
Requirement already satisfied: pillow in C:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages (from wordcloud) (12.2.0)
Requirement already satisfied: matplotlib in C:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages (from wordcloud) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages (from matplotlib->wordcloud) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages (from matplotlib->wordcloud) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\asrit\AppData\Roaming\Python\Python311\site-packages (from matplotlib->wordcloud) (26.2)
Requirement already satisfied: pyparsing>=3 in C:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages (from matplotlib->wordcloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\asrit\AppData\Roaming\Python\Python311\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\asrit\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)
Using cached wordcloud-1.9.6-cp311-cp311-win_amd64.whl (306 kB)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.9.6

In [26]:
import plotly.express as px
import plotly.graph_objects as go
# Join the cleaned text into a single string
text = ' '.join(df1['Processed_Resume'])

# Create a word cloud
wordcloud = WordCloud(background_color='white',
                      width=1000,
                      height=800,
                      max_words=500,
                      colormap='viridis'
                      ).generate(text)

# Convert word cloud to an image
wordcloud_image = wordcloud.to_image()

# Display the word cloud using Plotly as an image
fig = px.imshow(wordcloud_image)
fig.update_layout(
    title='Word Cloud of Cleaned Text',
    xaxis_showticklabels=False,
    yaxis_showticklabels=False,
    plot_bgcolor='white'
)
import plotly.io as pio
pio.renderers.default = "browser"

fig.show()

#### Encoding the Category column and plotting it

In [27]:
# Label encoding our Category
label = LabelEncoder()
df1['Encoded_Category'] = label.fit_transform(df1['Category'])
df1.head()

,Category,Resume,Processed_Resume,Encoded_Category
0,Data Science,Skills * Programming Languages: Python (pandas...,skill programming language python panda numpy ...,6
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,education detail may 2013 may 2017 b e uit rgp...,6
2,Data Science,"Areas of Interest Deep Learning, Control Syste...",area interest deep learning control system des...,6
3,Data Science,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,skill r python sap hana tableau sap hana sql s...,6
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",education detail mca ymcaust faridabad haryana...,6

In [28]:
df1['Category'].sample(15)

111                  Arts
289    Health and fitness
401        Java Developer
471    Automation Testing
73                     HR
766                Hadoop
333        Java Developer
819         ETL Developer
795         ETL Developer
556      Python Developer
430      Business Analyst
616       DevOps Engineer
942               Testing
817         ETL Developer
584      Python Developer
Name: Category, dtype: str

In [29]:
# Create the mapping
category_mapping = df1.groupby('Encoded_Category')['Category'].first().to_dict()

# Print the created mapping
print("Created Category Mapping:")
print(category_mapping)

Created Category Mapping:
{0: 'Advocate', 1: 'Arts', 2: 'Automation Testing', 3: 'Blockchain', 4: 'Business Analyst', 5: 'Civil Engineer', 6: 'Data Science', 7: 'Database', 8: 'DevOps Engineer', 9: 'DotNet Developer', 10: 'ETL Developer', 11: 'Electrical Engineering', 12: 'HR', 13: 'Hadoop', 14: 'Health and fitness', 15: 'Java Developer', 16: 'Mechanical Engineer', 17: 'Network Security Engineer', 18: 'Operations Manager', 19: 'PMO', 20: 'Python Developer', 21: 'SAP Developer', 22: 'Sales', 23: 'Testing', 24: 'Web Designing'}

### <b>#Vectorization (using TfidfVectorizer)</b>

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english',max_features=29033)

tfidf.fit(df1['Processed_Resume'])
requiredText  = tfidf.transform(df1['Processed_Resume'])
print(requiredText)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 155341 stored elements and shape (962, 6562)>
  Coords	Values
  (0, 118)	0.06453783899846323
  (0, 268)	0.04632697838273315
  (0, 298)	0.031126979945512483
  (0, 317)	0.025361912989866155
  (0, 340)	0.033319272390464866
  (0, 370)	0.029288428444891598
  (0, 495)	0.13903194496767213
  (0, 497)	0.07851286854091813
  (0, 500)	0.15656008367123686
  (0, 505)	0.02096423266463051
  (0, 512)	0.026190077390818307
  (0, 523)	0.04632697838273315
  (0, 526)	0.03727134831379874
  (0, 622)	0.04632697838273315
  (0, 640)	0.053810183291968954
  (0, 643)	0.08098518487138881
  (0, 645)	0.02899820504264113
  (0, 646)	0.06518168127424176
  (0, 650)	0.10712314267369262
  (0, 667)	0.03771995525102985
  (0, 700)	0.027461726023211917
  (0, 703)	0.03503454597093106
  (0, 786)	0.015483241225769256
  (0, 796)	0.08098518487138881
  (0, 829)	0.024012779374943182
  :	:
  (961, 5265)	0.040106642718727006
  (961, 5313)	0.034685407248807254
  (961, 5323)	0.04300525885009774
  (961, 5413)	0.029083167838973283
  (961, 5473)	0.08173539261801048
  (961, 5566)	0.03150101062479427
  (961, 5581)	0.041292506952808554
  (961, 5719)	0.056708709092727225
  (961, 5723)	0.07957384679896679
  (961, 5790)	0.07957384679896679
  (961, 5855)	0.0913986709054804
  (961, 5865)	0.02436657631243554
  (961, 5896)	0.1862621097482243
  (961, 5900)	0.38035443121688484
  (961, 5964)	0.06521703489339466
  (961, 6029)	0.13484105040549949
  (961, 6222)	0.03260851744669733
  (961, 6260)	0.07957384679896679
  (961, 6283)	0.07162623562714822
  (961, 6349)	0.17266809393032662
  (961, 6352)	0.07324363253410175
  (961, 6398)	0.07957384679896679
  (961, 6427)	0.17433779453582576
  (961, 6465)	0.4376490775067628
  (961, 6526)	0.22233129749407932

# <b>#Model Creation</b>

### <b>#Splitting into Train and Test using (Vectorized text & Encoded category)</b>

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(requiredText, df1['Encoded_Category'], test_size=0.35, random_state=42)
print(X_train.shape)

print(X_test.shape)

(625, 6562)
(337, 6562)

### <b>#Training the baseline model and printing its Accuracy</b>
- KNeighbors Classifier
- Multinomial NB

In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

mnb = MultinomialNB()
mnb.fit(X_train,y_train)
y_pred1 = mnb.predict(X_test)
print('Accuracy: ', accuracy_score(y_test,y_pred1)*100, ' % \n')
print(classification_report(y_test, y_pred1))

Accuracy:  90.50445103857567  %

              precision    recall  f1-score   support

           0       1.00      0.43      0.60         7
           1       1.00      1.00      1.00        12
           2       1.00      0.71      0.83         7
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00         9
           5       1.00      0.13      0.24        15
           6       1.00      1.00      1.00        13
           7       1.00      1.00      1.00        10
           8       1.00      0.90      0.95        21
           9       1.00      0.27      0.43        11
          10       1.00      1.00      1.00        10
          11       1.00      1.00      1.00        11
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        10
          14       1.00      1.00      1.00        12
          15       0.67      1.00      0.81        31
          16       1.00      1.00      1.00        14
          17       1.00      1.00      1.00         7
          18       1.00      1.00      1.00        19
          19       0.90      1.00      0.95         9
          20       1.00      1.00      1.00        16
          21       1.00      0.70      0.82        10
          22       1.00      1.00      1.00        12
          23       0.64      1.00      0.78        27
          24       0.92      1.00      0.96        12

    accuracy                           0.91       337
   macro avg       0.97      0.89      0.89       337
weighted avg       0.94      0.91      0.89       337

In [33]:
 knc = OneVsRestClassifier(KNeighborsClassifier())
 knc.fit(X_train,y_train)
 y_pred2 = knc.predict(X_test)
 print('Accuracy: ', accuracy_score(y_test,y_pred2)*100, ' %')
 print(classification_report(y_test, y_pred2))

Accuracy:  98.81305637982196  %
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         7
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00         9
           5       1.00      1.00      1.00        15
           6       1.00      0.85      0.92        13
           7       1.00      1.00      1.00        10
           8       1.00      0.90      0.95        21
           9       1.00      1.00      1.00        11
          10       1.00      1.00      1.00        10
          11       1.00      1.00      1.00        11
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        10
          14       1.00      1.00      1.00        12
          15       1.00      1.00      1.00        31
          16       1.00      1.00      1.00        14
          17       1.00      1.00      1.00         7
          18       0.95      1.00      0.97        19
          19       1.00      1.00      1.00         9
          20       1.00      1.00      1.00        16
          21       0.83      1.00      0.91        10
          22       1.00      1.00      1.00        12
          23       1.00      1.00      1.00        27
          24       0.92      1.00      0.96        12

    accuracy                           0.99       337
   macro avg       0.99      0.99      0.99       337
weighted avg       0.99      0.99      0.99       337

### <b>#Training the advanced model and printing its Accuracy</b>
- RNN

In [35]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, SpatialDropout1D
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.feature_extraction.text import TfidfVectorizer

# Define the maximum number of words to consider
max_words = 100

# Tokenize and pad sequences
tokenizer = Tokenizer(num_words=max_words, split=' ')
tokenizer.fit_on_texts(df1['Processed_Resume'])
X = tokenizer.texts_to_sequences(df1['Processed_Resume'])
X = pad_sequences(X, maxlen=100)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, df1['Encoded_Category'], test_size=0.25, random_state=42)

# Build the RNN model
model = Sequential()
model.add(Embedding(input_dim=max_words, output_dim=128, input_length=100))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100))
model.add(Dense(32, activation='relu'))
model.add(Dense(len(label.classes_), activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=150, batch_size=64)

# Evaluate the RNN model
# y_pred3 = model.predict(X_test)
y_pred_rnn_prob = model.predict(X_test)
y_pred3 = y_pred_rnn_prob.argmax(axis=-1)
accuracy_rnn = accuracy_score(y_test, y_pred3)
print('RNN Model Accuracy: {:.2f}%'.format(accuracy_rnn * 100))
print(classification_report(y_test, y_pred3))
# Accuracy is approx 61%

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/150

c:\Users\asrit\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 107ms/step - accuracy: 0.1415 - loss: 3.2004 - val_accuracy: 0.1784 - val_loss: 3.1601
Epoch 2/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.1165 - loss: 3.0724 - val_accuracy: 0.1992 - val_loss: 2.9080
Epoch 3/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.2691 - loss: 2.8078 - val_accuracy: 0.3900 - val_loss: 2.6619
Epoch 4/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.3523 - loss: 2.5327 - val_accuracy: 0.4149 - val_loss: 2.3810
Epoch 5/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 81ms/step - accuracy: 0.3592 - loss: 2.2866 - val_accuracy: 0.3817 - val_loss: 2.1941
Epoch 6/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 0.4619 - loss: 2.0971 - val_accuracy: 0.4149 - val_loss: 1.9661
Epoch 7/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 91ms/step - accuracy: 0.4799 - loss: 1.8771 - val_accuracy: 0.5062 - val_loss: 1.7902
Epoch 8/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 111ms/step - accuracy: 0.5201 - loss: 1.6875 - val_accuracy: 0.4979 - val_loss: 1.7562
Epoch 9/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 101ms/step - accuracy: 0.5423 - loss: 1.5323 - val_accuracy: 0.5394 - val_loss: 1.5093
Epoch 10/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 102ms/step - accuracy: 0.6463 - loss: 1.2781 - val_accuracy: 0.6556 - val_loss: 1.3031
Epoch 11/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 109ms/step - accuracy: 0.7379 - loss: 1.0524 - val_accuracy: 0.7054 - val_loss: 1.1173
Epoch 12/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 101ms/step - accuracy: 0.7753 - loss: 0.8516 - val_accuracy: 0.7344 - val_loss: 0.9500
Epoch 13/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 107ms/step - accuracy: 0.8128 - loss: 0.7194 - val_accuracy: 0.7635 - val_loss: 0.8299
Epoch 14/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 118ms/step - accuracy: 0.8599 - loss: 0.5633 - val_accuracy: 0.8174 - val_loss: 0.6475
Epoch 15/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 138ms/step - accuracy: 0.8849 - loss: 0.4942 - val_accuracy: 0.8257 - val_loss: 0.6872
Epoch 16/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 99ms/step - accuracy: 0.8641 - loss: 0.5232 - val_accuracy: 0.8216 - val_loss: 0.7286
Epoch 17/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 109ms/step - accuracy: 0.9307 - loss: 0.4354 - val_accuracy: 0.8838 - val_loss: 0.5032
Epoch 18/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 109ms/step - accuracy: 0.9293 - loss: 0.3151 - val_accuracy: 0.9253 - val_loss: 0.4536
Epoch 19/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 87ms/step - accuracy: 0.9570 - loss: 0.2570 - val_accuracy: 0.9087 - val_loss: 0.3765
Epoch 20/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 0.9653 - loss: 0.2019 - val_accuracy: 0.9295 - val_loss: 0.3348
Epoch 21/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 110ms/step - accuracy: 0.9667 - loss: 0.1672 - val_accuracy: 0.9544 - val_loss: 0.2842
Epoch 22/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 113ms/step - accuracy: 0.9820 - loss: 0.1397 - val_accuracy: 0.9585 - val_loss: 0.2475
Epoch 23/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 0.9847 - loss: 0.1133 - val_accuracy: 0.9502 - val_loss: 0.2271
Epoch 24/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 105ms/step - accuracy: 0.9847 - loss: 0.1063 - val_accuracy: 0.9544 - val_loss: 0.2421
Epoch 25/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 0.9875 - loss: 0.1057 - val_accuracy: 0.9793 - val_loss: 0.1985
Epoch 26/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 0.9903 - loss: 0.0825 - val_accuracy: 0.9627 - val_loss: 0.2235
Epoch 27/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 115ms/step - accuracy: 0.9917 - loss: 0.0705 - val_accuracy: 0.9793 - val_loss: 0.1773
Epoch 28/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - accuracy: 0.9917 - loss: 0.0727 - val_accuracy: 0.9668 - val_loss: 0.2051
Epoch 29/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 110ms/step - accuracy: 0.9667 - loss: 0.1369 - val_accuracy: 0.9461 - val_loss: 0.2596
Epoch 30/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 108ms/step - accuracy: 0.9834 - loss: 0.1030 - val_accuracy: 0.9793 - val_loss: 0.1979
Epoch 31/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 130ms/step - accuracy: 0.9889 - loss: 0.0975 - val_accuracy: 0.9544 - val_loss: 0.2877
Epoch 32/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 126ms/step - accuracy: 0.9834 - loss: 0.1105 - val_accuracy: 0.9834 - val_loss: 0.1828
Epoch 33/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 121ms/step - accuracy: 1.0000 - loss: 0.0495 - val_accuracy: 0.9834 - val_loss: 0.1624
Epoch 34/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 106ms/step - accuracy: 0.9986 - loss: 0.0359 - val_accuracy: 0.9834 - val_loss: 0.1656
Epoch 35/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 104ms/step - accuracy: 0.9986 - loss: 0.0350 - val_accuracy: 0.9834 - val_loss: 0.1653
Epoch 36/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 101ms/step - accuracy: 0.9986 - loss: 0.0273 - val_accuracy: 0.9834 - val_loss: 0.1440
Epoch 37/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 113ms/step - accuracy: 0.9945 - loss: 0.0363 - val_accuracy: 0.9461 - val_loss: 0.2529
Epoch 38/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 0.9917 - loss: 0.0471 - val_accuracy: 0.9585 - val_loss: 0.2253
Epoch 39/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 128ms/step - accuracy: 0.9820 - loss: 0.0665 - val_accuracy: 0.9834 - val_loss: 0.1796
Epoch 40/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 130ms/step - accuracy: 1.0000 - loss: 0.0365 - val_accuracy: 0.9834 - val_loss: 0.1656
Epoch 41/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 130ms/step - accuracy: 0.9972 - loss: 0.0271 - val_accuracy: 0.9834 - val_loss: 0.1587
Epoch 42/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 125ms/step - accuracy: 1.0000 - loss: 0.0187 - val_accuracy: 0.9834 - val_loss: 0.1583
Epoch 43/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 126ms/step - accuracy: 1.0000 - loss: 0.0155 - val_accuracy: 0.9834 - val_loss: 0.1565
Epoch 44/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 112ms/step - accuracy: 1.0000 - loss: 0.0131 - val_accuracy: 0.9834 - val_loss: 0.1605
Epoch 45/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 114ms/step - accuracy: 1.0000 - loss: 0.0110 - val_accuracy: 0.9834 - val_loss: 0.1604
Epoch 46/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 104ms/step - accuracy: 1.0000 - loss: 0.0099 - val_accuracy: 0.9834 - val_loss: 0.1616
Epoch 47/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 180ms/step - accuracy: 1.0000 - loss: 0.0089 - val_accuracy: 0.9834 - val_loss: 0.1633
Epoch 48/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 185ms/step - accuracy: 1.0000 - loss: 0.0082 - val_accuracy: 0.9834 - val_loss: 0.1651
Epoch 49/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 177ms/step - accuracy: 1.0000 - loss: 0.0080 - val_accuracy: 0.9834 - val_loss: 0.1666
Epoch 50/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 184ms/step - accuracy: 1.0000 - loss: 0.0070 - val_accuracy: 0.9834 - val_loss: 0.1666
Epoch 51/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 178ms/step - accuracy: 1.0000 - loss: 0.0069 - val_accuracy: 0.9834 - val_loss: 0.1683
Epoch 52/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 154ms/step - accuracy: 1.0000 - loss: 0.0063 - val_accuracy: 0.9834 - val_loss: 0.1687
Epoch 53/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 153ms/step - accuracy: 1.0000 - loss: 0.0061 - val_accuracy: 0.9834 - val_loss: 0.1694
Epoch 54/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.9834 - val_loss: 0.1704
Epoch 55/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 132ms/step - accuracy: 1.0000 - loss: 0.0055 - val_accuracy: 0.9834 - val_loss: 0.1721
Epoch 56/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 116ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.9834 - val_loss: 0.1639
Epoch 57/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 153ms/step - accuracy: 1.0000 - loss: 0.0053 - val_accuracy: 0.9834 - val_loss: 0.1650
Epoch 58/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 0.9834 - val_loss: 0.1688
Epoch 59/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 112ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.9834 - val_loss: 0.1713
Epoch 60/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 107ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.9834 - val_loss: 0.1712
Epoch 61/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 111ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.9834 - val_loss: 0.1711
Epoch 62/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 104ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.9834 - val_loss: 0.1701
Epoch 63/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 103ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.9834 - val_loss: 0.1686
Epoch 64/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 112ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.9834 - val_loss: 0.1672
Epoch 65/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 109ms/step - accuracy: 1.0000 - loss: 0.0036 - val_accuracy: 0.9834 - val_loss: 0.1720
Epoch 66/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 108ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.9834 - val_loss: 0.1757
Epoch 67/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.9834 - val_loss: 0.1777
Epoch 68/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 105ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.9834 - val_loss: 0.1755
Epoch 69/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 100ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.9834 - val_loss: 0.1738
Epoch 70/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 106ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.9834 - val_loss: 0.1742
Epoch 71/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 108ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9834 - val_loss: 0.1749
Epoch 72/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 104ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.9834 - val_loss: 0.1765
Epoch 73/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 110ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9834 - val_loss: 0.1827
Epoch 74/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 106ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.9834 - val_loss: 0.1831
Epoch 75/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 110ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.9834 - val_loss: 0.1848
Epoch 76/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 107ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.9834 - val_loss: 0.1838
Epoch 77/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 116ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.9834 - val_loss: 0.1800
Epoch 78/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 114ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9834 - val_loss: 0.1798
Epoch 79/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 118ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9834 - val_loss: 0.1795
Epoch 80/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 103ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9834 - val_loss: 0.1792
Epoch 81/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 112ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.9834 - val_loss: 0.1801
Epoch 82/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 106ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9834 - val_loss: 0.1808
Epoch 83/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9834 - val_loss: 0.1811
Epoch 84/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 186ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.9834 - val_loss: 0.1839
Epoch 85/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 176ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9834 - val_loss: 0.1856
Epoch 86/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 160ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9834 - val_loss: 0.1858
Epoch 87/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 195ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9834 - val_loss: 0.1836
Epoch 88/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 105ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9834 - val_loss: 0.1819
Epoch 89/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 143ms/step - accuracy: 0.9986 - loss: 0.0067 - val_accuracy: 0.9834 - val_loss: 0.1866
Epoch 90/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 138ms/step - accuracy: 0.9986 - loss: 0.0066 - val_accuracy: 0.9751 - val_loss: 0.1720
Epoch 91/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 108ms/step - accuracy: 0.9945 - loss: 0.0289 - val_accuracy: 0.9793 - val_loss: 0.1689
Epoch 92/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 106ms/step - accuracy: 0.9889 - loss: 0.0496 - val_accuracy: 0.9834 - val_loss: 0.1741
Epoch 93/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - accuracy: 0.9806 - loss: 0.0717 - val_accuracy: 0.9461 - val_loss: 0.2834
Epoch 94/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 90ms/step - accuracy: 0.9001 - loss: 0.3116 - val_accuracy: 0.8714 - val_loss: 0.4598
Epoch 95/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 115ms/step - accuracy: 0.8738 - loss: 0.4499 - val_accuracy: 0.8797 - val_loss: 0.4475
Epoch 96/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 175ms/step - accuracy: 0.9598 - loss: 0.2206 - val_accuracy: 0.9668 - val_loss: 0.2659
Epoch 97/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 207ms/step - accuracy: 0.9861 - loss: 0.1151 - val_accuracy: 0.9834 - val_loss: 0.1929
Epoch 98/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 214ms/step - accuracy: 0.9972 - loss: 0.0590 - val_accuracy: 0.9834 - val_loss: 0.1600
Epoch 99/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 185ms/step - accuracy: 1.0000 - loss: 0.0332 - val_accuracy: 0.9834 - val_loss: 0.1535
Epoch 100/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 142ms/step - accuracy: 1.0000 - loss: 0.0257 - val_accuracy: 0.9834 - val_loss: 0.1601
Epoch 101/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 182ms/step - accuracy: 1.0000 - loss: 0.0193 - val_accuracy: 0.9834 - val_loss: 0.1539
Epoch 102/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 146ms/step - accuracy: 1.0000 - loss: 0.0149 - val_accuracy: 0.9834 - val_loss: 0.1528
Epoch 103/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 151ms/step - accuracy: 1.0000 - loss: 0.0125 - val_accuracy: 0.9834 - val_loss: 0.1499
Epoch 104/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 138ms/step - accuracy: 1.0000 - loss: 0.0103 - val_accuracy: 0.9834 - val_loss: 0.1500
Epoch 105/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 148ms/step - accuracy: 1.0000 - loss: 0.0096 - val_accuracy: 0.9834 - val_loss: 0.1512
Epoch 106/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 132ms/step - accuracy: 1.0000 - loss: 0.0084 - val_accuracy: 0.9834 - val_loss: 0.1548
Epoch 107/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 118ms/step - accuracy: 1.0000 - loss: 0.0076 - val_accuracy: 0.9834 - val_loss: 0.1567
Epoch 108/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 99ms/step - accuracy: 1.0000 - loss: 0.0073 - val_accuracy: 0.9834 - val_loss: 0.1591
Epoch 109/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 162ms/step - accuracy: 1.0000 - loss: 0.0069 - val_accuracy: 0.9834 - val_loss: 0.1616
Epoch 110/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 171ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.9834 - val_loss: 0.1623
Epoch 111/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 162ms/step - accuracy: 0.9972 - loss: 0.0111 - val_accuracy: 0.9585 - val_loss: 0.2135
Epoch 112/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 148ms/step - accuracy: 0.9875 - loss: 0.0525 - val_accuracy: 0.9834 - val_loss: 0.1747
Epoch 113/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 149ms/step - accuracy: 0.9986 - loss: 0.0214 - val_accuracy: 0.9834 - val_loss: 0.1675
Epoch 114/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 141ms/step - accuracy: 0.9986 - loss: 0.0178 - val_accuracy: 0.9834 - val_loss: 0.1645
Epoch 115/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 163ms/step - accuracy: 0.9972 - loss: 0.0143 - val_accuracy: 0.9834 - val_loss: 0.1648
Epoch 116/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 138ms/step - accuracy: 1.0000 - loss: 0.0095 - val_accuracy: 0.9834 - val_loss: 0.1591
Epoch 117/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step - accuracy: 1.0000 - loss: 0.0057 - val_accuracy: 0.9834 - val_loss: 0.1602
Epoch 118/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 138ms/step - accuracy: 0.9986 - loss: 0.0121 - val_accuracy: 0.9834 - val_loss: 0.1672
Epoch 119/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 121ms/step - accuracy: 1.0000 - loss: 0.0059 - val_accuracy: 0.9834 - val_loss: 0.1684
Epoch 120/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 143ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.9834 - val_loss: 0.1675
Epoch 121/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 159ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.9834 - val_loss: 0.1669
Epoch 122/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 207ms/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.9834 - val_loss: 0.1675
Epoch 123/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 140ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.9834 - val_loss: 0.1697
Epoch 124/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.9834 - val_loss: 0.1702
Epoch 125/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 137ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.9834 - val_loss: 0.1693
Epoch 126/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 200ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.9834 - val_loss: 0.1686
Epoch 127/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 180ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.9834 - val_loss: 0.1705
Epoch 128/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 158ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.9834 - val_loss: 0.1738
Epoch 129/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 4s 272ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.9834 - val_loss: 0.1745
Epoch 130/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 162ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9834 - val_loss: 0.1750
Epoch 131/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 170ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.9834 - val_loss: 0.1759
Epoch 132/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 167ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9834 - val_loss: 0.1764
Epoch 133/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 147ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9834 - val_loss: 0.1767
Epoch 134/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 126ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9834 - val_loss: 0.1768
Epoch 135/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.9834 - val_loss: 0.1723
Epoch 136/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 123ms/step - accuracy: 0.9958 - loss: 0.0157 - val_accuracy: 0.9834 - val_loss: 0.1726
Epoch 137/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 135ms/step - accuracy: 0.9986 - loss: 0.0069 - val_accuracy: 0.9834 - val_loss: 0.1773
Epoch 138/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - accuracy: 0.9972 - loss: 0.0119 - val_accuracy: 0.9834 - val_loss: 0.1677
Epoch 139/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 135ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.9834 - val_loss: 0.1648
Epoch 140/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 225ms/step - accuracy: 0.9917 - loss: 0.0249 - val_accuracy: 0.9834 - val_loss: 0.1787
Epoch 141/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 221ms/step - accuracy: 0.9986 - loss: 0.0200 - val_accuracy: 0.9834 - val_loss: 0.1719
Epoch 142/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 5s 230ms/step - accuracy: 1.0000 - loss: 0.0078 - val_accuracy: 0.9834 - val_loss: 0.1721
Epoch 143/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 206ms/step - accuracy: 1.0000 - loss: 0.0051 - val_accuracy: 0.9834 - val_loss: 0.1700
Epoch 144/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 212ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.9834 - val_loss: 0.1761
Epoch 145/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 204ms/step - accuracy: 0.9972 - loss: 0.0080 - val_accuracy: 0.9834 - val_loss: 0.2006
Epoch 146/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 158ms/step - accuracy: 1.0000 - loss: 0.0084 - val_accuracy: 0.9834 - val_loss: 0.1972
Epoch 147/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 128ms/step - accuracy: 0.9958 - loss: 0.0156 - val_accuracy: 0.9834 - val_loss: 0.1875
Epoch 148/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 145ms/step - accuracy: 0.9972 - loss: 0.0075 - val_accuracy: 0.9834 - val_loss: 0.1851
Epoch 149/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 159ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.9834 - val_loss: 0.1833
Epoch 150/150
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 148ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.9834 - val_loss: 0.1889
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step
RNN Model Accuracy: 98.34%
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         6
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         6
           3       1.00      1.00      1.00        10
           4       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         9

# <b>Prediction & Recommendation System</b>

#### <b>Saving the created models</b>

In [36]:
import pickle
pickle.dump(tfidf,open('tfidf.pkl','wb'))
pickle.dump(mnb, open('mnb.pkl', 'wb'))
pickle.dump(tokenizer, open('rnn_tokenizer.pkl','wb'))
pickle.dump(model, open('rnn.pkl', 'wb'))

In [37]:
import tensorflow as tf
print(tf.__version__)

2.21.0

In [38]:
resume_1 = """I am a data scientist specializing in machine
learning, deep learning, and computer vision. With
a strong background in mathematics, statistics,
and programming, I am passionate about
uncovering hidden patterns and insights in data.
I have extensive experience in developing
predictive models, implementing deep learning
algorithms, and designing computer vision
systems. My technical skills include proficiency in
Python, Sklearn, TensorFlow, and PyTorch.
What sets me apart is my ability to effectively
communicate complex concepts to diverse
audiences. I excel in translating technical insights
into actionable recommendations that drive
informed decision-making.
If you're looking for a dedicated and versatile data
scientist to collaborate on impactful projects, I am
eager to contribute my expertise. Let's harness the
power of data together to unlock new possibilities
and shape a better future.
Contact & Sources
Email: 611noorsaeed@gmail.com
Phone: 03442826192
Github: https://github.com/611noorsaeed
Linkdin: https://www.linkedin.com/in/noor-saeed654a23263/
Blogs: https://medium.com/@611noorsaeed
Youtube: Artificial Intelligence
ABOUT ME
WORK EXPERIENCE
SKILLES
NOOR SAEED
LANGUAGES
English
Urdu
Hindi
I am a versatile data scientist with expertise in a wide
range of projects, including machine learning,
recommendation systems, deep learning, and computer
vision. Throughout my career, I have successfully
developed and deployed various machine learning models
to solve complex problems and drive data-driven
decision-making
Machine Learnine
Deep Learning
Computer Vision
Recommendation Systems
Data Visualization
Programming Languages (Python, SQL)
Data Preprocessing and Feature Engineering
Model Evaluation and Deployment
Statistical Analysis
Communication and Collaboration
"""

In [39]:
resume_1 = """
John A. Smith
(555) 555-5555
john.smith@example.com
1 Main Street, Seattle, WA 98133

Profile
A Senior Software Engineer with six years of professional experience, specializing in fullstack development, MySQL, Oracle, and Python. A proven track record of managing large scale software engineering projects to support cloud deployments and integrations.

Professional Experience
Senior Software Engineer, Microsoft, Los Angeles, CA
August 2019-Current

Manage a software engineering team of 15+ personnel to build innovative web applications using Agile-Waterfall methodologies, oversee all aspects of full-stack development, and identify opportunities to enhance the user experience
Identify creative solutions and workflow optimizations to improve deployment timelines and reduce project roadblocks during development lifecycles
Serve as the Microsoft Azure SME for the software engineering department and resolve escalated software issues from junior team members
Software Engineer, Uber, Los Angeles, CA
June 2017-August 2019

Coordinated with a team of 30+ software engineers to re-engineer the system into a PHP-based 3-tier application for a global rideshare company with 300M users
Supported projects to improve geo transit data application tools for drivers and users, which contributed to a 20% increase in user satisfaction
Certifications
MCPS: Microsoft Certified Professional
LPIC-3 Senior Level Linux Certification
Code Camp Trainer
Oracle Certified Professional – Java SE Programmer
Microsoft Certified Solutions Developer
Google Certified Professional Cloud Architect
Key Skills
Application Development
Java/Python/C++/Ruby/Perl/PHP/React/Angular
Full-stack developer
MySQL/Oracle/RedHat/AIX
Analysis and visualization of data structures
Education
Master of Business Administration, Information Systems
California State University, Long Beach, CA, September 2018 – July 2020

Bachelor of Computer Science, Software Engineering Major
University of California, Los Angeles, CA, August 2015 – July 2018, 4.0 GPA


"""

#### <b> Predicting Resume-1 by KNearestClassifier model</b>

In [40]:
"""
import pickle

# Load the trained KNearest classifier model
clf = pickle.load(open('knc.pkl', 'rb'))

# Clean the input resume
cleaned_resume = resumeKeywords(resume_1)

# Transform the cleaned resume using the trained TfidfVectorizer
input_features = tfidf.transform([cleaned_resume])

# Make the prediction using the loaded classifier
prediction_id = clf.predict(input_features)[0]

category_name = category_mapping.get(prediction_id, "Unknown")

print("Predicted Category:", category_name)
print(prediction_id)
"""

'\nimport pickle\n\n# Load the trained KNearest classifier model\nclf = pickle.load(open(\'knc.pkl\', \'rb\'))\n\n# Clean the input resume\ncleaned_resume = resumeKeywords(resume_1)\n\n# Transform the cleaned resume using the trained TfidfVectorizer\ninput_features = tfidf.transform([cleaned_resume])\n\n# Make the prediction using the loaded classifier\nprediction_id = clf.predict(input_features)[0]\n\ncategory_name = category_mapping.get(prediction_id, "Unknown")\n\nprint("Predicted Category:", category_name)\nprint(prediction_id)\n'

#### <b> Predicting Resume-1 by Multinomial Naive Bayes model</b>

In [41]:
import pickle

# Load the trained  Multinomial Naive Bayes model
mnb = pickle.load(open('mnb.pkl', 'rb'))

# Clean the input resume
cleaned_resume = resumeKeywords(resume_1)

# Transform the cleaned resume using the trained TfidfVectorizer
input_features = tfidf.transform([cleaned_resume])

# Make the prediction using the loaded classifier
prediction_id = mnb.predict(input_features)[0]

category_name = category_mapping.get(prediction_id, "Unknown")

print("Predicted Category:", category_name)
print(prediction_id)

Predicted Category: Java Developer
15

#### <b> Predicting Resume-1 by RNN model</b>

In [42]:
import pickle
rnn = pickle.load(open('rnn.pkl', 'rb'))
rnn_tokenizer = pickle.load(open('rnn_tokenizer.pkl', 'rb'))
# Define the maximum number of words to consider
max_words = 5000
cleaned_resume = resumeKeywords(resume_1)  # Clean the input resume

# Tokenize the cleaned input resume
input_sequence = rnn_tokenizer.texts_to_sequences([cleaned_resume])
# Padding the sequences
input_sequence = pad_sequences(input_sequence, maxlen=100)

# Make the prediction using the loaded RNN model
predicted_probabilities = rnn.predict(input_sequence)

prediction_id = predicted_probabilities.argmax(axis=-1)
# Map the category ID to the category name using category_mapping
category_name = category_mapping.get(prediction_id[0], "Unknown")

print("Predicted Category:", category_name)
print("Predicted Category ID:", prediction_id[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 440ms/step
Predicted Category: Java Developer
Predicted Category ID: 15

In [43]:
job_description_1="""
About the job
Join a top employer and advance your career. Aplin has partnered with an Edmonton-based company to hire a Data Scientist. 

In this exciting role, you will serve as the catalyst for data-driven decision-making, guiding our client toward unparalleled success in lead conversion, customer loyalty, predictive innovation, and inventory optimization. 

Responsibilities:
Dive deep into datasets to unveil the untapped potential in enhancing lead conversion rates.
Develop cutting-edge algorithms that predict customer preferences.
Pioneer loyalty programs that exert a magnetic influence, guaranteeing a continuous stream of returning customers.
Optimize inventory with precision, ensuring the right products are available at the right time.
Qualifications:
Bachelor's degree in Computer Science, Statistics, Applied Math, or related fields; a Master's or PhD will give your credentials an extra boost.
Proficiency in SQL, Python, R, or any other data manipulation language.
Hands-on experience in machine learning, predictive analytics, and various statistical modeling techniques.
Exceptional attention to detail, capable of identifying outliers in datasets with precision.
A passion for storytelling through data, recognizing the importance of context in making impactful decisions.
Outstanding collaboration skills to navigate seamlessly within teams, ensuring smooth progress on your journey.

"""

In [44]:
job_description_1="""
My technical skills include proficiency in
Python, Sklearn, TensorFlow, and PyTorch.
What sets me apart is my ability to effectively
communicate complex concepts to diverse
audiences. I excel in translating technical insights
into actionable recommendations that drive
informed decision-making.

ABOUT ME
WORK EXPERIENCE
SKILLES
NOOR SAEED
LANGUAGES
English
Urdu
Hindi
I am a versatile data scientist with expertise in a wide
range of projects, including machine learning,
recommendation systems, deep learning, and computer
vision. Throughout my career, I have successfully
developed and deployed various machine learning models
to solve complex problems and drive data-driven
decision-making
Machine Learnine
Deep Learning
Computer Vision
Recommendation Systems
Data Visualization
Programming Languages (Python, SQL)
Data Preprocessing and Feature Engineering
Model Evaluation and Deployment
Statistical Analysis
Communication and Collaboration
"""

In [45]:
job_description_1 = """
LMI is seeking a Software Developer or computer science graduate with 7+ years of proven experience in computer vision who has the desire and skill set to design machine vision sensors. You will work in a multi-disciplinary, multi-platform, engineering team (software, electrical, mechanical/optical) that develops new sensor products and supporting infrastructure (manufacturing and test equipment). The ideal candidate will have a passion for leading-edge technology, extensive experience developing production-ready software, strong critical thinking and problem-solving skills, and can work well autonomously yet still communicate effectively with a close-knit group of about 10 engineers. Previous leadership or project management experience is an asset as there is an opportunity to lead a team in this role.

This Senior Software Developer will work in the R&D team and report to the Software Engineering Manager.

Design and develop 3D acquisition algorithms for our sensors to produce 3D data from images
Develop components of our calibration and acquisition pipeline
Characterize and validate prototype sensor performance and integrate final designs with customers
Investigate solutions for challenging acquisition problems. Investigate improvements to our algorithms to enhance the performance of our sensors
Design and develop manufacturing software tools required to build the sensors and control key component performance (e.g. software tasks for focusing and aligning cameras/lasers/projectors, quantifying and adjusting sensor sensitivity, etc.)
Lead technical investigations and produce reports and documentation for senior management
Demonstrate leadership and ownership. Drive projects to completion, participate in frequent peer design and code reviews, and use your expertise to oversee and mentor others in the team
Proactively contribute to and implement continuous improvement initiatives
What do you need to be successful?

Degree / Diploma in Computer Science, Electrical/Computer Engineering or equivalent
5+ years work experience in a disciplined software development environment producing deliverable code
Solid knowledge of C/C++ and C# programming using Microsoft Visual Studio
Expertise in 3D metrology or computer vision (object detection, image restoration, scene reconstruction, signal processing, etc., but excluding machine learning) is required
Experience independently planning and completing complex projects/deliverables in a reliable time frame
Proficient with commonly used scripting languages like Python
Excellent understanding of object-oriented programming
Excellent understanding of commonly used data structures and algorithms (lists, trees, sorting, binning, etc.)
Excellent understanding of math and statistics
Excellent written and verbal communication
Solid understanding of memory management, threading/synchronization, networking
Previous scrum master experience or experience overseeing a small team is an asset
Experience developing for a manufacturing automation environment is an asset
Salary Range: $106,000 - $132,500 - $151,000

Expected Salary: Our typical hiring range will be +/- 10% of the midpoint listed above. Factors influencing this decision include qualifications and market conditions for the role.
"""

# Keywords extraction from provided Job Description and Resume

In [46]:
from sklearn.metrics.pairwise import cosine_similarity
cleaned_resume = resumeKeywords(resume_1)
cleaned_job_description = resumeKeywords(job_description_1)
vectors_1  = tfidf.transform([cleaned_resume])
vectors_2 = tfidf.transform([cleaned_job_description])
similarity_score = cosine_similarity(vectors_1,vectors_2)
print("Similarity Score:", similarity_score)

Similarity Score: [[0.1385646]]

# <b>Bulding Job Category Recommendation System for this dataset</b>

- Shape of the vectors

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_1 = TfidfVectorizer(stop_words='english',max_features=500)

tfidf_1.fit(df1['Processed_Resume'][0:5000])
requiredText  = tfidf_1.transform(df1['Processed_Resume'][0:5000])
print(requiredText)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 75037 stored elements and shape (962, 500)>
  Coords	Values
  (0, 14)	0.11917052199112144
  (0, 19)	0.04683132340033452
  (0, 26)	0.25672550727384724
  (0, 28)	0.28909159624200015
  (0, 30)	0.03871091112683252
  (0, 32)	0.0483605469610782
  (0, 41)	0.05070867379121967
  (0, 49)	0.028590141343798472
  (0, 52)	0.044340118866356124
  (0, 57)	0.05028821612874323
  (0, 61)	0.07654866197897492
  (0, 65)	0.0719702584573859
  (0, 72)	0.05039720138168771
  (0, 73)	0.05070867379121967
  (0, 74)	0.05229137607332689
  (0, 81)	0.013663795865860006
  (0, 86)	0.027070376970601738
  (0, 98)	0.035912642077968696
  (0, 100)	0.04545615080886045
  (0, 103)	0.12534629571459246
  (0, 108)	0.08516543454198569
  (0, 110)	0.08295077192276187
  (0, 112)	0.1472979313066486
  (0, 113)	0.2753802431379583
  (0, 114)	0.026014592123072208
  :	:
  (961, 358)	0.1201836986931062
  (961, 364)	0.0327113401255411
  (961, 370)	0.040841179529759235
  (961, 379)	0.0337219082126757
  (961, 380)	0.08988500206796182
  (961, 384)	0.029015361316596773
  (961, 388)	0.029736629453543665
  (961, 394)	0.12973530632560537
  (961, 405)	0.04464727290685546
  (961, 407)	0.03861227812518517
  (961, 409)	0.04787405272926864
  (961, 414)	0.032375787238262656
  (961, 417)	0.09098897671286112
  (961, 424)	0.035067363480669404
  (961, 427)	0.04596739347792475
  (961, 450)	0.1017462726027539
  (961, 452)	0.027125211902093594
  (961, 453)	0.20734957309833854
  (961, 454)	0.4234158468702425
  (961, 457)	0.07260051097973642
  (961, 462)	0.1501069341236666
  (961, 480)	0.03630025548986821
  (961, 488)	0.19407525943291828
  (961, 491)	0.4871970445871859
  (961, 498)	0.24750229493326428

In [48]:
vectors = requiredText.toarray()
print(vectors.shape)
print(vectors[0])

(962, 500)
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.11917052 0.         0.         0.
 0.         0.04683132 0.         0.         0.         0.
 0.         0.         0.25672551 0.         0.2890916  0.
 0.03871091 0.         0.04836055 0.         0.         0.
 0.         0.         0.         0.         0.         0.05070867
 0.         0.         0.         0.         0.         0.
 0.         0.02859014 0.         0.         0.04434012 0.
 0.         0.         0.         0.05028822 0.         0.
 0.         0.07654866 0.         0.         0.         0.07197026
 0.         0.         0.         0.         0.         0.
 0.0503972  0.05070867 0.05229138 0.         0.         0.
 0.         0.         0.         0.0136638  0.         0.
 0.         0.         0.02707038 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.03591264 0.         0.04545615 0.
 0.         0.1253463  0.         0.         0.         0.
 0.08516543 0.         0.08295077 0.         0.14729793 0.27538024
 0.02601459 0.         0.         0.         0.         0.
 0.         0.         0.         0.0136638  0.         0.
 0.         0.         0.         0.07392844 0.         0.03440811
 0.0259796  0.         0.         0.03171336 0.         0.
 0.         0.         0.         0.         0.         0.
 0.01640414 0.04294074 0.         0.         0.         0.
 0.         0.07027935 0.         0.         0.         0.03785127
 0.         0.         0.09033696 0.         0.         0.05049683
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.05140272
 0.         0.         0.         0.04071407 0.         0.
 0.         0.04381452 0.04699303 0.         0.         0.
 0.         0.         0.         0.04211949 0.05229138 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.04020981
 0.         0.         0.         0.         0.         0.
 0.         0.07226253 0.         0.0818422  0.04651355 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.24551501 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.03129451 0.         0.03083817 0.1555581
 0.         0.         0.17033087 0.         0.         0.
 0.         0.         0.08907264 0.         0.         0.
 0.         0.08268964 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.04270102
 0.         0.         0.         0.         0.03844729 0.
 0.         0.03340939 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.03562648 0.         0.         0.         0.         0.09431333
 0.         0.         0.         0.03500372 0.03811162 0.
 0.01713424 0.         0.07603785 0.         0.         0.03402498
 0.         0.         0.         0.04502689 0.         0.
 0.         0.         0.         0.         0.         0.0343435
 0.         0.         0.         0.03972351 0.07983192 0.
 0.         0.         0.         0.         0.         0.
 0.         0.04102581 0.         0.         0.         0.
 0.         0.         0.17742807 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.04394404 0.         0.         0.
 0.         0.02780914 0.09062312 0.06575624 0.         0.
 0.         0.         0.03665542 0.         0.02028881 0.
 0.         0.         0.         0.         0.         0.
 0.         0.2208537  0.04929042 0.         0.         0.
 0.         0.         0.05028822 0.06804997 0.         0.
 0.         0.02846382 0.07586968 0.         0.         0.
 0.02449114 0.0433084  0.         0.         0.         0.
 0.04167146 0.         0.34547795 0.04258272 0.         0.
 0.         0.         0.         0.         0.10059094 0.
 0.         0.         0.         0.03768565 0.         0.
 0.02533126 0.         0.         0.         0.         0.
 0.02732759 0.         0.         0.         0.02915145 0.
 0.0786931  0.         0.         0.         0.02959948 0.
 0.         0.         0.         0.         0.03591264 0.
 0.         0.         0.         0.04620299 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.02144215
 0.         0.         0.13737427 0.         0.         0.21314218
 0.         0.06128027 0.         0.         0.21747521 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.0430622  0.03981939 0.
 0.         0.         0.         0.         0.         0.0348691
 0.09192041 0.02737658 0.02846382 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.22875004 0.         0.02950869 0.         0.         0.
 0.         0.02412015]

In [49]:
vectors

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02412015],
       [0.        , 0.11056736, 0.        , ..., 0.        , 0.        ,
        0.40667888],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.41077046],
       ...,
       [0.02572716, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.09660559],
       [0.16587966, 0.        , 0.        , ..., 0.        , 0.24750229,
        0.        ]], shape=(962, 500))

- Gives the total number of frequent words in the corpus

In [50]:
len(tfidf_1.get_feature_names_out())

500

- Gives the list of most frequent words to less frequent words in the corpus

In [51]:
print(tfidf_1.get_feature_names_out())

['10' '12' '15' '20' '2008' '2010' '2011' '2012' '2013' '2014' '2015'
 '2016' '2017' '2018' '24' '48' 'ability' 'access' 'account' 'action'
 'activity' 'admin' 'administration' 'administrator' 'agile' 'ajax'
 'analysis' 'analyst' 'analytics' 'analyze' 'analyzing' 'android'
 'angular' 'api' 'application' 'architecture' 'area' 'art' 'asp'
 'attending' 'audit' 'automated' 'automation' 'aws' 'bachelor' 'backup'
 'bank' 'banking' 'base' 'based' 'basic' 'basis' 'best' 'billing'
 'blockchain' 'bo' 'board' 'bootstrap' 'branch' 'budget' 'bug' 'build'
 'building' 'business' 'card' 'case' 'center' 'certificate' 'change'
 'check' 'cisco' 'civil' 'client' 'cloud' 'cluster' 'code' 'college' 'com'
 'commerce' 'commercial' 'communication' 'company' 'complete' 'completed'
 'compliance' 'component' 'computer' 'conducted' 'configuration'
 'construction' 'consultancy' 'consultant' 'contract' 'contribution'
 'control' 'controller' 'coordinate' 'coordinating' 'core' 'corporate'
 'cost' 'course' 'create' 'created' 'creating' 'creation' 'credit'
 'critical' 'cs' 'css3' 'customer' 'daily' 'dashboard' 'data' 'database'
 'date' 'day' 'db' 'defect' 'deliverable' 'delivery' 'department'
 'deployment' 'description' 'design' 'designed' 'designer' 'designing'
 'develop' 'developed' 'developer' 'developing' 'development' 'device'
 'devops' 'different' 'diploma' 'distribution' 'document' 'documentation'
 'dr' 'drawing' 'duration' 'duty' 'education' 'effective' 'efficiency'
 'electrical' 'electronics' 'email' 'employee' 'end' 'engineer'
 'engineering' 'english' 'ensure' 'ensuring' 'enterprise' 'entire'
 'environment' 'equipment' 'erp' 'estimation' 'ethereum' 'etl' 'event'
 'excel' 'excellent' 'execution' 'existing' 'experience' 'expertise'
 'export' 'exprience' 'fat' 'feature' 'field' 'file' 'financial'
 'firewall' 'fitness' 'flow' 'following' 'framework' 'freight' 'function'
 'functional' 'gathering' 'ge' 'generate' 'git' 'given' 'global' 'goal'
 'good' 'graphic' 'group' 'hadoop' 'hana' 'handled' 'handling' 'hdfs'
 'health' 'help' 'hibernate' 'high' 'hive' 'honeywell' 'hotel' 'hr' 'hsc'
 'html' 'html5' 'identify' 'identifying' 'implementation' 'implemented'
 'implementing' 'includes' 'including' 'india' 'industrial' 'industry'
 'informatica' 'information' 'infrastructure' 'inspection' 'installation'
 'institute' 'insurance' 'integration' 'interface' 'internal'
 'international' 'inventory' 'involved' 'issue' 'january' 'java'
 'javascript' 'jenkins' 'job' 'jquery' 'jsp' 'june' 'key' 'knowledge'
 'korea' 'language' 'layer' 'lead' 'leader' 'leading' 'learning' 'level'
 'life' 'like' 'limited' 'line' 'linux' 'load' 'loan' 'log' 'machine'
 'maharashtra' 'maintain' 'maintaining' 'maintenance' 'make' 'manage'
 'management' 'manager' 'managing' 'manual' 'manufacturing' 'mapping'
 'marketing' 'master' 'material' 'mechanical' 'medium' 'meeting' 'member'
 'methodology' 'mi' 'microsoft' 'migration' 'model' 'module' 'monitor'
 'monitored' 'monitoring' 'month' 'monthly' 'monthscompany' 'multi'
 'multiple' 'mumbai' 'mvc' 'mysql' 'nagpur' 'nashik' 'need' 'net'
 'network' 'networking' 'new' 'offer' 'office' 'online' 'operating'
 'operation' 'operational' 'opportunity' 'oracle' 'order' 'organization'
 'overall' 'panel' 'participate' 'participated' 'payment' 'people'
 'perform' 'performance' 'performed' 'personal' 'photoshop' 'php' 'plan'
 'planning' 'plant' 'platform' 'plc' 'pmo' 'point' 'policy' 'portal'
 'position' 'power' 'pre' 'preparation' 'prepare' 'preparing' 'present'
 'presentation' 'private' 'problem' 'procedure' 'process' 'processing'
 'product' 'production' 'professional' 'profile' 'program' 'programming'
 'progress' 'project' 'proposal' 'provide' 'provided' 'provider'
 'providing' 'pune' 'purchase' 'pvt' 'python' 'qa' 'qtp' 'quality' 'query'
 'record' 'reduce' 'regression' 'related' 'relationship' 'release'
 'replication' 'report' 'reporting' 'repository' 'request' 'required'
 'requirement' 'research' 'resolve' 'resource' 'responsibility'
 'responsible' 'result' 'revenue' 'review' 'risk' 'role' 'router' 'sale'
 'sap' 'schedule' 'school' 'science' 'scope' 'script' 'scripting'
 'secondary' 'security' 'senior' 'server' 'service' 'set' 'shell'
 'shipment' 'site' 'size' 'skill' 'sla' 'smooth' 'software' 'solution'
 'solving' 'source' 'spark' 'specification' 'spring' 'sql' 'sqoop' 'sr'
 'ssc' 'staff' 'stakeholder' 'standard' 'state' 'station' 'status' 'stock'
 'store' 'strategy' 'strong' 'student' 'studio' 'successfully' 'supplier'
 'supply' 'support' 'table' 'talend' 'target' 'task' 'tata' 'team' 'tech'
 'technical' 'technology' 'test' 'testing' 'text' 'till' 'time' 'timely'
 'title' 'tool' 'track' 'tracking' 'training' 'transaction' 'transformer'
 'troubleshooting' 'trust' 'type' 'uat' 'ui' 'understand' 'understanding'
 'unit' 'university' 'unix' 'update' 'upgrade' 'use' 'used' 'user' 'using'
 'various' 'vendor' 'version' 'view' 'visual' 'warehouse' 'web' 'website'
 'weekly' 'window' 'word' 'work' 'worked' 'working' 'workshop' 'writing'
 'xp' 'year']

- Looking for most frequent word at certain indexes

In [52]:
print(tfidf_1.get_feature_names_out()[40])
print(tfidf_1.get_feature_names_out()[20])
print(tfidf_1.get_feature_names_out()[11])
print(tfidf_1.get_feature_names_out()[22])
print(tfidf_1.get_feature_names_out()[33])
print(tfidf_1.get_feature_names_out()[44])

audit
activity
2016
administration
api
bachelor

### Similarity Score (Cosine similarity method)
- For recommending the similar job category we need to identify the nearest vectors of a particular job category vector.
- In order to find out the nearest vectors, we use similarity score and it has two methods (1- Euclidean distance method) & (2- Cosine similarity method)
- Here, I will be using cosine similarity method rather than euclidean distance method because euclidean distance does not perform well on higher dimensions
- The similarity is inverse of distance. [0-1]
- If 1 then similarity is high and if 0 then similarity is low

In [53]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
# This will create result with values as distance/similarity between each vectors
print(similarity)

[[1.         0.21285366 0.29135787 ... 0.04283016 0.06877198 0.09435305]
 [0.21285366 1.         0.50844088 ... 0.01732533 0.18809417 0.10409007]
 [0.29135787 0.50844088 1.         ... 0.03952149 0.28214179 0.19174322]
 ...
 [0.04283016 0.01732533 0.03952149 ... 1.         0.12282746 0.24562413]
 [0.06877198 0.18809417 0.28214179 ... 0.12282746 1.         0.18933751]
 [0.09435305 0.10409007 0.19174322 ... 0.24562413 0.18933751 1.        ]]

In [54]:
print(similarity.shape)
# It finds out distance of each job with every job, and that is the reason why the shape of the similarity shape is (5000,5000)
print(similarity[0])
# Gives similarity score of first job with every job, it can also be seen that the first value is 1 which indicates that the value is the
# similarity score of first job with itself.
print(similarity[1])

(962, 962)
[1.         0.21285366 0.29135787 0.31853294 0.2448193  0.22845056
 0.39632279 0.37209677 0.32211525 0.43922873 1.         0.21285366
 0.29135787 0.31853294 0.2448193  0.22845056 0.39632279 0.37209677
 0.32211525 0.43922873 1.         0.21285366 0.29135787 0.31853294
 0.2448193  0.22845056 0.39632279 0.37209677 0.32211525 0.43922873
 1.         0.21285366 0.29135787 0.31853294 0.2448193  0.22845056
 0.39632279 0.37209677 0.32211525 0.43922873 0.01816578 0.10834576
 0.03095514 0.01709607 0.01709607 0.02570113 0.01125132 0.0463916
 0.00808838 0.04966654 0.12702822 0.01816578 0.10834576 0.03095514
 0.01709607 0.01709607 0.02570113 0.01125132 0.0463916  0.00808838
 0.04966654 0.12702822 0.01816578 0.10834576 0.03095514 0.01709607
 0.01709607 0.02570113 0.01125132 0.0463916  0.00808838 0.04966654
 0.12702822 0.01816578 0.10834576 0.03095514 0.01709607 0.01709607
 0.02570113 0.01125132 0.0463916  0.00808838 0.04966654 0.12702822
 0.02961909 0.05244453 0.05619823 0.09642719 0.11514494 0.00679563
 0.0284009  0.03259584 0.04093093 0.00410334 0.02961909 0.05244453
 0.05619823 0.09642719 0.11514494 0.00679563 0.0284009  0.03259584
 0.04093093 0.00410334 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.13048535 0.18865909 0.13048535 0.07227875
 0.26997976 0.13048535 0.18865909 0.13048535 0.07227875 0.26997976
 0.13048535 0.18865909 0.13048535 0.07227875 0.26997976 0.13048535
 0.18865909 0.13048535 0.07227875 0.26997976 0.13048535 0.18865909
 0.13048535 0.07227875 0.26997976 0.13048535 0.18865909 0.13048535
 0.07227875 0.26997976 0.13048535 0.18865909 0.13048535 0.07227875
 0.26997976 0.13048535 0.18865909 0.13048535 0.07227875 0.26997976
 0.13048535 0.18865909 0.13048535 0.07227875 0.26997976 0.16792914
 0.04237394 0.01765808 0.0272114  0.06921091 0.16792914 0.04237394
 0.01765808 0.0272114  0.06921091 0.16792914 0.04237394 0.01765808
 0.0272114  0.06921091 0.16792914 0.04237394 0.01765808 0.0272114
 0.06921091 0.16792914 0.04237394 0.01765808 0.0272114  0.06921091
 0.16792914 0.04237394 0.01765808 0.0272114  0.06921091 0.16792914
 0.04237394 0.01765808 0.0272114  0.06921091 0.16792914 0.04237394
 0.01765808 0.0272114  0.06921091 0.08453302 0.05366758 0.08669874
 0.05750105 0.08128779 0.08453302 0.05366758 0.08669874 0.05750105
 0.08128779 0.08453302 0.05366758 0.08669874 0.05750105 0.08128779
 0.08453302 0.05366758 0.08669874 0.05750105 0.08128779 0.08453302
 0.05366758 0.08669874 0.05750105 0.08128779 0.08453302 0.05366758
 0.08669874 0.05750105 0.08128779 0.08453302 0.05366758 0.08669874
 0.05750105 0.08128779 0.08453302 0.05366758 0.08669874 0.05750105
 0.08128779 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.06836609 0.02531673 0.06557649 0.02895641 0.04053079
 0.01646453 0.06836609 0.02531673 0.06557649 0.02895641 0.04053079
 0.01646453 0.06836609 0.02531673 0.06557649 0.02895641 0.04053079
 0.01646453 0.06836609 0.02531673 0.06557649 0.02895641 0.04053079
 0.01646453 0.09699884 0.07816594 0.14573704 0.18674605 0.19628721
 0.13065252 0.13794257 0.13794257 0.15350264 0.13382518 0.20924301
 0.18886928 0.11532029 0.08720851 0.09699884 0.07816594 0.14573704
 0.18674605 0.19628721 0.13065252 0.13794257 0.13794257 0.15350264
 0.13382518 0.20924301 0.18886928 0.11532029 0.08720851 0.09699884
 0.07816594 0.14573704 0.18674605 0.19628721 0.13065252 0.13794257
 0.13794257 0.15350264 0.13382518 0.20924301 0.18886928 0.11532029
 0.08720851 0.09699884 0.07816594 0.14573704 0.18674605 0.19628721
 0.13065252 0.13794257 0.13794257 0.15350264 0.13382518 0.20924301
 0.18886928 0.11532029 0.08720851 0.09699884 0.07816594 0.14573704
 0.18674605 0.19628721 0.13065252 0.13794257 0.13794257 0.15350264
 0.13382518 0.20924301 0.18886928 0.11532029 0.08720851 0.09699884
 0.07816594 0.14573704 0.18674605 0.19628721 0.13065252 0.13794257
 0.13794257 0.15350264 0.13382518 0.20924301 0.18886928 0.11532029
 0.08720851 0.14198373 0.1816746  0.19449934 0.23692325 0.08990265
 0.09656212 0.19449934 0.23692325 0.08990265 0.09656212 0.19449934
 0.23692325 0.08990265 0.09656212 0.14198373 0.1816746  0.19449934
 0.23692325 0.08990265 0.09656212 0.19449934 0.23692325 0.08990265
 0.09656212 0.19449934 0.23692325 0.08990265 0.09656212 0.15647445
 0.18911404 0.09835453 0.09326609 0.06732697 0.0879665  0.15647445
 0.18911404 0.09835453 0.09326609 0.06732697 0.0879665  0.15647445
 0.18911404 0.09835453 0.09326609 0.06732697 0.0879665  0.15647445
 0.18911404 0.09835453 0.09326609 0.06732697 0.0879665  0.12215433
 0.04606581 0.16428028 0.14505966 0.10991572 0.12379592 0.07003588
 0.14505966 0.10991572 0.14505966 0.10991572 0.14505966 0.10991572
 0.12215433 0.04606581 0.16428028 0.14505966 0.10991572 0.12379592
 0.07003588 0.14505966 0.10991572 0.14505966 0.10991572 0.14505966
 0.10991572 0.07393591 0.03117341 0.08426961 0.01397281 0.03675132
 0.07393591 0.03117341 0.08426961 0.01397281 0.03675132 0.07393591
 0.03117341 0.08426961 0.01397281 0.03675132 0.07393591 0.03117341
 0.08426961 0.01397281 0.03675132 0.07393591 0.03117341 0.08426961
 0.01397281 0.03675132 0.07393591 0.03117341 0.08426961 0.01397281
 0.03675132 0.22592797 0.13113626 0.10796109 0.11402537 0.22592797
 0.13113626 0.10796109 0.11402537 0.22592797 0.13113626 0.10796109
 0.11402537 0.22592797 0.13113626 0.10796109 0.11402537 0.22592797
 0.13113626 0.10796109 0.11402537 0.22592797 0.13113626 0.10796109
 0.11402537 0.22592797 0.13113626 0.10796109 0.11402537 0.22592797
 0.13113626 0.10796109 0.11402537 0.22592797 0.13113626 0.10796109
 0.11402537 0.22592797 0.13113626 0.10796109 0.11402537 0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.15093537
 0.21676266 0.18412373 0.18518507 0.1429393  0.130036   0.12477678
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.08555815 0.08901657 0.09980418 0.07472228 0.03950846 0.08555815
 0.08901657 0.09980418 0.07472228 0.03950846 0.08555815 0.08901657
 0.09980418 0.07472228 0.03950846 0.08555815 0.08901657 0.09980418
 0.07472228 0.03950846 0.08555815 0.08901657 0.09980418 0.07472228
 0.03950846 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.10315151 0.11267458 0.08815501 0.13547122 0.08245933
 0.12780753 0.18682523 0.08966562 0.12703074 0.10398621 0.23635817
 0.10315151 0.11267458 0.08815501 0.13547122 0.08245933 0.12780753
 0.18682523 0.08966562 0.12703074 0.10398621 0.23635817 0.10315151
 0.11267458 0.08815501 0.13547122 0.08245933 0.12780753 0.18682523
 0.08966562 0.12703074 0.10398621 0.23635817 0.19488374 0.11152504
 0.23006098 0.20931224 0.22244507 0.16640446 0.30162455 0.19488374
 0.11152504 0.23006098 0.20931224 0.22244507 0.16640446 0.30162455
 0.19488374 0.11152504 0.23006098 0.20931224 0.22244507 0.16640446
 0.30162455 0.19488374 0.11152504 0.23006098 0.20931224 0.22244507
 0.16640446 0.30162455 0.19488374 0.11152504 0.23006098 0.20931224
 0.22244507 0.16640446 0.30162455 0.19488374 0.11152504 0.23006098
 0.20931224 0.22244507 0.16640446 0.30162455 0.20023509 0.14005807
 0.10387064 0.14999186 0.0788719  0.20023509 0.14005807 0.10387064
 0.14999186 0.0788719  0.20023509 0.14005807 0.10387064 0.14999186
 0.0788719  0.20023509 0.14005807 0.10387064 0.14999186 0.0788719
 0.20023509 0.14005807 0.10387064 0.14999186 0.0788719  0.20023509
 0.14005807 0.10387064 0.14999186 0.0788719  0.20023509 0.14005807
 0.10387064 0.14999186 0.0788719  0.20023509 0.14005807 0.10387064
 0.14999186 0.0788719  0.24335462 0.10732695 0.21480334 0.08155645
 0.14690326 0.1894933  0.18918674 0.24335462 0.10732695 0.21480334
 0.08155645 0.14690326 0.1894933  0.18918674 0.24335462 0.10732695
 0.21480334 0.08155645 0.14690326 0.1894933  0.18918674 0.24335462
 0.10732695 0.21480334 0.08155645 0.14690326 0.1894933  0.18918674
 0.10429179 0.19647964 0.16250161 0.13292371 0.23207599 0.10429179
 0.19647964 0.16250161 0.13292371 0.23207599 0.10429179 0.19647964
 0.16250161 0.13292371 0.23207599 0.10429179 0.19647964 0.16250161
 0.13292371 0.23207599 0.10429179 0.19647964 0.16250161 0.13292371
 0.23207599 0.10429179 0.19647964 0.16250161 0.13292371 0.23207599
 0.10429179 0.19647964 0.16250161 0.13292371 0.23207599 0.10429179
 0.19647964 0.16250161 0.13292371 0.23207599 0.02196895 0.09458239
 0.04335546 0.07255309 0.04283016 0.06877198 0.09435305 0.02196895
 0.09458239 0.04335546 0.07255309 0.04283016 0.06877198 0.09435305
 0.02196895 0.09458239 0.04335546 0.07255309 0.04283016 0.06877198
 0.09435305 0.02196895 0.09458239 0.04335546 0.07255309 0.04283016
 0.06877198 0.09435305 0.02196895 0.09458239 0.04335546 0.07255309
 0.04283016 0.06877198 0.09435305 0.02196895 0.09458239 0.04335546
 0.07255309 0.04283016 0.06877198 0.09435305 0.02196895 0.09458239
 0.04335546 0.07255309 0.04283016 0.06877198 0.09435305 0.02196895
 0.09458239 0.04335546 0.07255309 0.04283016 0.06877198 0.09435305
 0.02196895 0.09458239 0.04335546 0.07255309 0.04283016 0.06877198
 0.09435305 0.02196895 0.09458239 0.04335546 0.07255309 0.04283016
 0.06877198 0.09435305]
[0.21285366 1.         0.50844088 0.21963994 0.61228559 0.49563672
 0.38988779 0.4404475  0.32243297 0.32212917 0.21285366 1.
 0.50844088 0.21963994 0.61228559 0.49563672 0.38988779 0.4404475
 0.32243297 0.32212917 0.21285366 1.         0.50844088 0.21963994
 0.61228559 0.49563672 0.38988779 0.4404475  0.32243297 0.32212917
 0.21285366 1.         0.50844088 0.21963994 0.61228559 0.49563672
 0.38988779 0.4404475  0.32243297 0.32212917 0.14236688 0.04342433
 0.15501927 0.03688998 0.03688998 0.18703014 0.04143422 0.21827383
 0.05196214 0.18019536 0.22977675 0.14236688 0.04342433 0.15501927
 0.03688998 0.03688998 0.18703014 0.04143422 0.21827383 0.05196214
 0.18019536 0.22977675 0.14236688 0.04342433 0.15501927 0.03688998
 0.03688998 0.18703014 0.04143422 0.21827383 0.05196214 0.18019536
 0.22977675 0.14236688 0.04342433 0.15501927 0.03688998 0.03688998
 0.18703014 0.04143422 0.21827383 0.05196214 0.18019536 0.22977675
 0.03546243 0.37563007 0.40118208 0.49437736 0.21585139 0.02445695
 0.023912   0.0652418  0.16286869 0.08458692 0.03546243 0.37563007
 0.40118208 0.49437736 0.21585139 0.02445695 0.023912   0.0652418
 0.16286869 0.08458692 0.05790579 0.13395544 0.14223628 0.23388653
 0.19780815 0.23460892 0.05790579 0.13395544 0.14223628 0.23388653
 0.19780815 0.23460892 0.05790579 0.13395544 0.14223628 0.23388653
 0.19780815 0.23460892 0.05790579 0.13395544 0.14223628 0.23388653
 0.19780815 0.23460892 0.05790579 0.13395544 0.14223628 0.23388653
 0.19780815 0.23460892 0.05790579 0.13395544 0.14223628 0.23388653
 0.19780815 0.23460892 0.16464487 0.01015612 0.16464487 0.12821692
 0.19094108 0.16464487 0.01015612 0.16464487 0.12821692 0.19094108
 0.16464487 0.01015612 0.16464487 0.12821692 0.19094108 0.16464487
 0.01015612 0.16464487 0.12821692 0.19094108 0.16464487 0.01015612
 0.16464487 0.12821692 0.19094108 0.16464487 0.01015612 0.16464487
 0.12821692 0.19094108 0.16464487 0.01015612 0.16464487 0.12821692
 0.19094108 0.16464487 0.01015612 0.16464487 0.12821692 0.19094108
 0.16464487 0.01015612 0.16464487 0.12821692 0.19094108 0.03516682
 0.26757562 0.02639495 0.06964269 0.20614995 0.03516682 0.26757562
 0.02639495 0.06964269 0.20614995 0.03516682 0.26757562 0.02639495
 0.06964269 0.20614995 0.03516682 0.26757562 0.02639495 0.06964269
 0.20614995 0.03516682 0.26757562 0.02639495 0.06964269 0.20614995
 0.03516682 0.26757562 0.02639495 0.06964269 0.20614995 0.03516682
 0.26757562 0.02639495 0.06964269 0.20614995 0.03516682 0.26757562
 0.02639495 0.06964269 0.20614995 0.4827482  0.21731308 0.09700844
 0.18580623 0.09293609 0.4827482  0.21731308 0.09700844 0.18580623
 0.09293609 0.4827482  0.21731308 0.09700844 0.18580623 0.09293609
 0.4827482  0.21731308 0.09700844 0.18580623 0.09293609 0.4827482
 0.21731308 0.09700844 0.18580623 0.09293609 0.4827482  0.21731308
 0.09700844 0.18580623 0.09293609 0.4827482  0.21731308 0.09700844
 0.18580623 0.09293609 0.4827482  0.21731308 0.09700844 0.18580623
 0.09293609 0.05190906 0.03501754 0.04981015 0.06024772 0.08783437
 0.07398163 0.05190906 0.03501754 0.04981015 0.06024772 0.08783437
 0.07398163 0.05190906 0.03501754 0.04981015 0.06024772 0.08783437
 0.07398163 0.05190906 0.03501754 0.04981015 0.06024772 0.08783437
 0.07398163 0.05190906 0.03501754 0.04981015 0.06024772 0.08783437
 0.07398163 0.03585125 0.03997846 0.11390875 0.02382121 0.1206959
 0.046705   0.03585125 0.03997846 0.11390875 0.02382121 0.1206959
 0.046705   0.03585125 0.03997846 0.11390875 0.02382121 0.1206959
 0.046705   0.03585125 0.03997846 0.11390875 0.02382121 0.1206959
 0.046705   0.08832085 0.12610524 0.05334891 0.11886885 0.0620971
 0.37765483 0.28260184 0.28260184 0.1416759  0.23370233 0.00944908
 0.21177152 0.05938698 0.18086012 0.08832085 0.12610524 0.05334891
 0.11886885 0.0620971  0.37765483 0.28260184 0.28260184 0.1416759
 0.23370233 0.00944908 0.21177152 0.05938698 0.18086012 0.08832085
 0.12610524 0.05334891 0.11886885 0.0620971  0.37765483 0.28260184
 0.28260184 0.1416759  0.23370233 0.00944908 0.21177152 0.05938698
 0.18086012 0.08832085 0.12610524 0.05334891 0.11886885 0.0620971
 0.37765483 0.28260184 0.28260184 0.1416759  0.23370233 0.00944908
 0.21177152 0.05938698 0.18086012 0.08832085 0.12610524 0.05334891
 0.11886885 0.0620971  0.37765483 0.28260184 0.28260184 0.1416759
 0.23370233 0.00944908 0.21177152 0.05938698 0.18086012 0.08832085
 0.12610524 0.05334891 0.11886885 0.0620971  0.37765483 0.28260184
 0.28260184 0.1416759  0.23370233 0.00944908 0.21177152 0.05938698
 0.18086012 0.04746504 0.12970139 0.15332329 0.11761067 0.14901642
 0.07057338 0.15332329 0.11761067 0.14901642 0.07057338 0.15332329
 0.11761067 0.14901642 0.07057338 0.04746504 0.12970139 0.15332329
 0.11761067 0.14901642 0.07057338 0.15332329 0.11761067 0.14901642
 0.07057338 0.15332329 0.11761067 0.14901642 0.07057338 0.17061892
 0.07767283 0.09446438 0.05246626 0.03287622 0.15726262 0.17061892
 0.07767283 0.09446438 0.05246626 0.03287622 0.15726262 0.17061892
 0.07767283 0.09446438 0.05246626 0.03287622 0.15726262 0.17061892
 0.07767283 0.09446438 0.05246626 0.03287622 0.15726262 0.07528401
 0.04502282 0.14252916 0.07995317 0.119981   0.10425715 0.19190334
 0.07995317 0.119981   0.07995317 0.119981   0.07995317 0.119981
 0.07528401 0.04502282 0.14252916 0.07995317 0.119981   0.10425715
 0.19190334 0.07995317 0.119981   0.07995317 0.119981   0.07995317
 0.119981   0.07318203 0.0449286  0.04108771 0.08453299 0.08264786
 0.07318203 0.0449286  0.04108771 0.08453299 0.08264786 0.07318203
 0.0449286  0.04108771 0.08453299 0.08264786 0.07318203 0.0449286
 0.04108771 0.08453299 0.08264786 0.07318203 0.0449286  0.04108771
 0.08453299 0.08264786 0.07318203 0.0449286  0.04108771 0.08453299
 0.08264786 0.08438611 0.09578867 0.08151455 0.01918404 0.08438611
 0.09578867 0.08151455 0.01918404 0.08438611 0.09578867 0.08151455
 0.01918404 0.08438611 0.09578867 0.08151455 0.01918404 0.08438611
 0.09578867 0.08151455 0.01918404 0.08438611 0.09578867 0.08151455
 0.01918404 0.08438611 0.09578867 0.08151455 0.01918404 0.08438611
 0.09578867 0.08151455 0.01918404 0.08438611 0.09578867 0.08151455
 0.01918404 0.08438611 0.09578867 0.08151455 0.01918404 0.16117036
 0.09929837 0.19660281 0.29765905 0.14382968 0.27084527 0.16117036
 0.09929837 0.19660281 0.29765905 0.14382968 0.27084527 0.16117036
 0.09929837 0.19660281 0.29765905 0.14382968 0.27084527 0.16117036
 0.09929837 0.19660281 0.29765905 0.14382968 0.27084527 0.16117036
 0.09929837 0.19660281 0.29765905 0.14382968 0.27084527 0.16117036
 0.09929837 0.19660281 0.29765905 0.14382968 0.27084527 0.16117036
 0.09929837 0.19660281 0.29765905 0.14382968 0.27084527 0.16117036
 0.09929837 0.19660281 0.29765905 0.14382968 0.27084527 0.14024968
 0.41835857 0.10502234 0.11336145 0.13929957 0.24387075 0.11788831
 0.14024968 0.41835857 0.10502234 0.14024968 0.41835857 0.10502234
 0.14024968 0.41835857 0.10502234 0.14024968 0.41835857 0.10502234
 0.14024968 0.41835857 0.10502234 0.14024968 0.41835857 0.10502234
 0.14024968 0.41835857 0.10502234 0.14024968 0.41835857 0.10502234
 0.14024968 0.41835857 0.10502234 0.14024968 0.41835857 0.10502234
 0.14024968 0.41835857 0.10502234 0.14024968 0.41835857 0.10502234
 0.14024968 0.41835857 0.10502234 0.14024968 0.41835857 0.10502234
 0.14024968 0.41835857 0.10502234 0.14024968 0.41835857 0.10502234
 0.20655481 0.37066976 0.0604242  0.04780808 0.04073927 0.20655481
 0.37066976 0.0604242  0.04780808 0.04073927 0.20655481 0.37066976
 0.0604242  0.04780808 0.04073927 0.20655481 0.37066976 0.0604242
 0.04780808 0.04073927 0.20655481 0.37066976 0.0604242  0.04780808
 0.04073927 0.11538741 0.07812129 0.11788441 0.11538741 0.07812129
 0.11788441 0.11538741 0.07812129 0.11788441 0.11538741 0.07812129
 0.11788441 0.11538741 0.07812129 0.11788441 0.11538741 0.07812129
 0.11788441 0.11538741 0.07812129 0.11788441 0.11538741 0.07812129
 0.11788441 0.11538741 0.07812129 0.11788441 0.11538741 0.07812129
 0.11788441 0.088312   0.0364693  0.10770936 0.08537227 0.03707008
 0.14617684 0.0887084  0.10053761 0.11939815 0.01797863 0.33322858
 0.088312   0.0364693  0.10770936 0.08537227 0.03707008 0.14617684
 0.0887084  0.10053761 0.11939815 0.01797863 0.33322858 0.088312
 0.0364693  0.10770936 0.08537227 0.03707008 0.14617684 0.0887084
 0.10053761 0.11939815 0.01797863 0.33322858 0.06581834 0.12573427
 0.09714035 0.14047372 0.21521263 0.15911452 0.08837929 0.06581834
 0.12573427 0.09714035 0.14047372 0.21521263 0.15911452 0.08837929
 0.06581834 0.12573427 0.09714035 0.14047372 0.21521263 0.15911452
 0.08837929 0.06581834 0.12573427 0.09714035 0.14047372 0.21521263
 0.15911452 0.08837929 0.06581834 0.12573427 0.09714035 0.14047372
 0.21521263 0.15911452 0.08837929 0.06581834 0.12573427 0.09714035
 0.14047372 0.21521263 0.15911452 0.08837929 0.11442482 0.10216647
 0.05984902 0.09677368 0.17465092 0.11442482 0.10216647 0.05984902
 0.09677368 0.17465092 0.11442482 0.10216647 0.05984902 0.09677368
 0.17465092 0.11442482 0.10216647 0.05984902 0.09677368 0.17465092
 0.11442482 0.10216647 0.05984902 0.09677368 0.17465092 0.11442482
 0.10216647 0.05984902 0.09677368 0.17465092 0.11442482 0.10216647
 0.05984902 0.09677368 0.17465092 0.11442482 0.10216647 0.05984902
 0.09677368 0.17465092 0.28248938 0.16046795 0.16809027 0.07755662

In [55]:
df2 = df1
df2 = df2[['Category','Resume','Processed_Resume','Encoded_Category']][0:5000]
df2.head()

,Category,Resume,Processed_Resume,Encoded_Category
0,Data Science,Skills * Programming Languages: Python (pandas...,skill programming language python panda numpy ...,6
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,education detail may 2013 may 2017 b e uit rgp...,6
2,Data Science,"Areas of Interest Deep Learning, Control Syste...",area interest deep learning control system des...,6
3,Data Science,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,skill r python sap hana tableau sap hana sql s...,6
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",education detail mca ymcaust faridabad haryana...,6

In [56]:
df2['Encoded_Category'].value_counts()

Encoded_Category
15    84
23    70
8     55
20    48
24    45
12    44
13    42
6     40
16    40
22    40
18    40
10    40
3     40
1     36
7     33
14    30
11    30
19    30
4     28
9     28
2     26
17    25
5     24
21    24
0     20
Name: count, dtype: int64

### Creating function which will recommend top 5 job categories based on the predicted job category 

1) Initially, if the predicted job category id is given, I will need to find out the index of that job category in my dataset
2) Based on index value, I will be able to know the list of similarity scores of that particular job category with every job category
3) Using Enumerate function to align index and values together while sorting the similarity score in descending order to get top-5 job category

1) Based on given predicted job category id getting the index of that job category in my dataset

In [63]:
for cat in [0, 38, 26]:
    rows = df2[df2['Encoded_Category'] == cat]
    
    if len(rows) > 0:
        print(cat, rows.index[0])
    else:
        print(cat, "not found")

0 84
38 not found
26 not found

2) Based on the fetched index getting the similarity score list of that job

3) Now as I need the top 5 similar job categories I will need to sort the data in descending order to get top-5.
- However, there is a problem if I am sorting, the index position is getting lost. So, to solve this problem I am using enumerate function (which prints index with value)
- Applying lambda function in that to sort in descending order according to the similarity score and not based on the index value.

In [58]:
# 2.------------------------------- 
print(similarity[0])
print(similarity[38]) 
print(similarity[26]) 
# 3.------------------------------- 
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(list(enumerate(similarity[0]))) 
print(list(enumerate(similarity[38]))) 
print(list(enumerate(similarity[26]))) 
print("-------------------------------------------------------------------------------------------------------------------------------------")
print(sorted(list(enumerate(similarity[0])),reverse = True, key=lambda x:x[1])) 
print(sorted(list(enumerate(similarity[38])),reverse = True, key=lambda x:x[1])) 
print(sorted(list(enumerate(similarity[26])),reverse = True, key=lambda x:x[1]))

[1.         0.21285366 0.29135787 0.31853294 0.2448193  0.22845056
 0.39632279 0.37209677 0.32211525 0.43922873 1.         0.21285366
 0.29135787 0.31853294 0.2448193  0.22845056 0.39632279 0.37209677
 0.32211525 0.43922873 1.         0.21285366 0.29135787 0.31853294
 0.2448193  0.22845056 0.39632279 0.37209677 0.32211525 0.43922873
 1.         0.21285366 0.29135787 0.31853294 0.2448193  0.22845056
 0.39632279 0.37209677 0.32211525 0.43922873 0.01816578 0.10834576
 0.03095514 0.01709607 0.01709607 0.02570113 0.01125132 0.0463916
 0.00808838 0.04966654 0.12702822 0.01816578 0.10834576 0.03095514
 0.01709607 0.01709607 0.02570113 0.01125132 0.0463916  0.00808838
 0.04966654 0.12702822 0.01816578 0.10834576 0.03095514 0.01709607
 0.01709607 0.02570113 0.01125132 0.0463916  0.00808838 0.04966654
 0.12702822 0.01816578 0.10834576 0.03095514 0.01709607 0.01709607
 0.02570113 0.01125132 0.0463916  0.00808838 0.04966654 0.12702822
 0.02961909 0.05244453 0.05619823 0.09642719 0.11514494 0.00679563
 0.0284009  0.03259584 0.04093093 0.00410334 0.02961909 0.05244453
 0.05619823 0.09642719 0.11514494 0.00679563 0.0284009  0.03259584
 0.04093093 0.00410334 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.03299655 0.00566126 0.06441357 0.01508513
 0.02854308 0.04469036 0.13048535 0.18865909 0.13048535 0.07227875
 0.26997976 0.13048535 0.18865909 0.13048535 0.07227875 0.26997976
 0.13048535 0.18865909 0.13048535 0.07227875 0.26997976 0.13048535
 0.18865909 0.13048535 0.07227875 0.26997976 0.13048535 0.18865909
 0.13048535 0.07227875 0.26997976 0.13048535 0.18865909 0.13048535
 0.07227875 0.26997976 0.13048535 0.18865909 0.13048535 0.07227875
 0.26997976 0.13048535 0.18865909 0.13048535 0.07227875 0.26997976
 0.13048535 0.18865909 0.13048535 0.07227875 0.26997976 0.16792914
 0.04237394 0.01765808 0.0272114  0.06921091 0.16792914 0.04237394
 0.01765808 0.0272114  0.06921091 0.16792914 0.04237394 0.01765808
 0.0272114  0.06921091 0.16792914 0.04237394 0.01765808 0.0272114
 0.06921091 0.16792914 0.04237394 0.01765808 0.0272114  0.06921091
 0.16792914 0.04237394 0.01765808 0.0272114  0.06921091 0.16792914
 0.04237394 0.01765808 0.0272114  0.06921091 0.16792914 0.04237394
 0.01765808 0.0272114  0.06921091 0.08453302 0.05366758 0.08669874
 0.05750105 0.08128779 0.08453302 0.05366758 0.08669874 0.05750105
 0.08128779 0.08453302 0.05366758 0.08669874 0.05750105 0.08128779
 0.08453302 0.05366758 0.08669874 0.05750105 0.08128779 0.08453302
 0.05366758 0.08669874 0.05750105 0.08128779 0.08453302 0.05366758
 0.08669874 0.05750105 0.08128779 0.08453302 0.05366758 0.08669874
 0.05750105 0.08128779 0.08453302 0.05366758 0.08669874 0.05750105
 0.08128779 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.03857056 0.01605455 0.05868552 0.05163215 0.09006621
 0.14805147 0.06836609 0.02531673 0.06557649 0.02895641 0.04053079
 0.01646453 0.06836609 0.02531673 0.06557649 0.02895641 0.04053079
 0.01646453 0.06836609 0.02531673 0.06557649 0.02895641 0.04053079
 0.01646453 0.06836609 0.02531673 0.06557649 0.02895641 0.04053079
 0.01646453 0.09699884 0.07816594 0.14573704 0.18674605 0.19628721
 0.13065252 0.13794257 0.13794257 0.15350264 0.13382518 0.20924301
 0.18886928 0.11532029 0.08720851 0.09699884 0.07816594 0.14573704
 0.18674605 0.19628721 0.13065252 0.13794257 0.13794257 0.15350264
 0.13382518 0.20924301 0.18886928 0.11532029 0.08720851 0.09699884
 0.07816594 0.14573704 0.18674605 0.19628721 0.13065252 0.13794257
 0.13794257 0.15350264 0.13382518 0.20924301 0.18886928 0.11532029
 0.08720851 0.09699884 0.07816594 0.14573704 0.18674605 0.19628721
 0.13065252 0.13794257 0.13794257 0.15350264 0.13382518 0.20924301
 0.18886928 0.11532029 0.08720851 0.09699884 0.07816594 0.14573704
 0.18674605 0.19628721 0.13065252 0.13794257 0.13794257 0.15350264
 0.13382518 0.20924301 0.18886928 0.11532029 0.08720851 0.09699884
 0.07816594 0.14573704 0.18674605 0.19628721 0.13065252 0.13794257
 0.13794257 0.15350264 0.13382518 0.20924301 0.18886928 0.11532029
 0.08720851 0.14198373 0.1816746  0.19449934 0.23692325 0.08990265
 0.09656212 0.19449934 0.23692325 0.08990265 0.09656212 0.19449934
 0.23692325 0.08990265 0.09656212 0.14198373 0.1816746  0.19449934
 0.23692325 0.08990265 0.09656212 0.19449934 0.23692325 0.08990265
 0.09656212 0.19449934 0.23692325 0.08990265 0.09656212 0.15647445
 0.18911404 0.09835453 0.09326609 0.06732697 0.0879665  0.15647445
 0.18911404 0.09835453 0.09326609 0.06732697 0.0879665  0.15647445
 0.18911404 0.09835453 0.09326609 0.06732697 0.0879665  0.15647445
 0.18911404 0.09835453 0.09326609 0.06732697 0.0879665  0.12215433
 0.04606581 0.16428028 0.14505966 0.10991572 0.12379592 0.07003588
 0.14505966 0.10991572 0.14505966 0.10991572 0.14505966 0.10991572
 0.12215433 0.04606581 0.16428028 0.14505966 0.10991572 0.12379592
 0.07003588 0.14505966 0.10991572 0.14505966 0.10991572 0.14505966
 0.10991572 0.07393591 0.03117341 0.08426961 0.01397281 0.03675132
 0.07393591 0.03117341 0.08426961 0.01397281 0.03675132 0.07393591
 0.03117341 0.08426961 0.01397281 0.03675132 0.07393591 0.03117341
 0.08426961 0.01397281 0.03675132 0.07393591 0.03117341 0.08426961
 0.01397281 0.03675132 0.07393591 0.03117341 0.08426961 0.01397281
 0.03675132 0.22592797 0.13113626 0.10796109 0.11402537 0.22592797
 0.13113626 0.10796109 0.11402537 0.22592797 0.13113626 0.10796109
 0.11402537 0.22592797 0.13113626 0.10796109 0.11402537 0.22592797
 0.13113626 0.10796109 0.11402537 0.22592797 0.13113626 0.10796109
 0.11402537 0.22592797 0.13113626 0.10796109 0.11402537 0.22592797
 0.13113626 0.10796109 0.11402537 0.22592797 0.13113626 0.10796109
 0.11402537 0.22592797 0.13113626 0.10796109 0.11402537 0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.17634263
 0.12673855 0.19999018 0.28607779 0.06853369 0.2011792  0.15093537
 0.21676266 0.18412373 0.18518507 0.1429393  0.130036   0.12477678
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.15093537 0.21676266 0.18412373 0.15093537 0.21676266 0.18412373
 0.08555815 0.08901657 0.09980418 0.07472228 0.03950846 0.08555815
 0.08901657 0.09980418 0.07472228 0.03950846 0.08555815 0.08901657
 0.09980418 0.07472228 0.03950846 0.08555815 0.08901657 0.09980418
 0.07472228 0.03950846 0.08555815 0.08901657 0.09980418 0.07472228
 0.03950846 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.25521471 0.14900212 0.12031811 0.25521471 0.14900212
 0.12031811 0.10315151 0.11267458 0.08815501 0.13547122 0.08245933
 0.12780753 0.18682523 0.08966562 0.12703074 0.10398621 0.23635817
 0.10315151 0.11267458 0.08815501 0.13547122 0.08245933 0.12780753
 0.18682523 0.08966562 0.12703074 0.10398621 0.23635817 0.10315151
 0.11267458 0.08815501 0.13547122 0.08245933 0.12780753 0.18682523
 0.08966562 0.12703074 0.10398621 0.23635817 0.19488374 0.11152504
 0.23006098 0.20931224 0.22244507 0.16640446 0.30162455 0.19488374
 0.11152504 0.23006098 0.20931224 0.22244507 0.16640446 0.30162455
 0.19488374 0.11152504 0.23006098 0.20931224 0.22244507 0.16640446
 0.30162455 0.19488374 0.11152504 0.23006098 0.20931224 0.22244507
 0.16640446 0.30162455 0.19488374 0.11152504 0.23006098 0.20931224
 0.22244507 0.16640446 0.30162455 0.19488374 0.11152504 0.23006098
 0.20931224 0.22244507 0.16640446 0.30162455 0.20023509 0.14005807
 0.10387064 0.14999186 0.0788719  0.20023509 0.14005807 0.10387064
 0.14999186 0.0788719  0.20023509 0.14005807 0.10387064 0.14999186
 0.0788719  0.20023509 0.14005807 0.10387064 0.14999186 0.0788719
 0.20023509 0.14005807 0.10387064 0.14999186 0.0788719  0.20023509
 0.14005807 0.10387064 0.14999186 0.0788719  0.20023509 0.14005807
 0.10387064 0.14999186 0.0788719  0.20023509 0.14005807 0.10387064
 0.14999186 0.0788719  0.24335462 0.10732695 0.21480334 0.08155645
 0.14690326 0.1894933  0.18918674 0.24335462 0.10732695 0.21480334
 0.08155645 0.14690326 0.1894933  0.18918674 0.24335462 0.10732695
 0.21480334 0.08155645 0.14690326 0.1894933  0.18918674 0.24335462
 0.10732695 0.21480334 0.08155645 0.14690326 0.1894933  0.18918674
 0.10429179 0.19647964 0.16250161 0.13292371 0.23207599 0.10429179
 0.19647964 0.16250161 0.13292371 0.23207599 0.10429179 0.19647964
 0.16250161 0.13292371 0.23207599 0.10429179 0.19647964 0.16250161
 0.13292371 0.23207599 0.10429179 0.19647964 0.16250161 0.13292371
 0.23207599 0.10429179 0.19647964 0.16250161 0.13292371 0.23207599
 0.10429179 0.19647964 0.16250161 0.13292371 0.23207599 0.10429179
 0.19647964 0.16250161 0.13292371 0.23207599 0.02196895 0.09458239
 0.04335546 0.07255309 0.04283016 0.06877198 0.09435305 0.02196895
 0.09458239 0.04335546 0.07255309 0.04283016 0.06877198 0.09435305
 0.02196895 0.09458239 0.04335546 0.07255309 0.04283016 0.06877198
 0.09435305 0.02196895 0.09458239 0.04335546 0.07255309 0.04283016
 0.06877198 0.09435305 0.02196895 0.09458239 0.04335546 0.07255309
 0.04283016 0.06877198 0.09435305 0.02196895 0.09458239 0.04335546
 0.07255309 0.04283016 0.06877198 0.09435305 0.02196895 0.09458239
 0.04335546 0.07255309 0.04283016 0.06877198 0.09435305 0.02196895
 0.09458239 0.04335546 0.07255309 0.04283016 0.06877198 0.09435305
 0.02196895 0.09458239 0.04335546 0.07255309 0.04283016 0.06877198
 0.09435305 0.02196895 0.09458239 0.04335546 0.07255309 0.04283016
 0.06877198 0.09435305]
[0.32211525 0.32243297 0.4446582  0.22564203 0.1994529  0.4221218
 0.51475589 0.662121   1.         0.41675482 0.32211525 0.32243297
 0.4446582  0.22564203 0.1994529  0.4221218  0.51475589 0.662121
 1.         0.41675482 0.32211525 0.32243297 0.4446582  0.22564203
 0.1994529  0.4221218  0.51475589 0.662121   1.         0.41675482
 0.32211525 0.32243297 0.4446582  0.22564203 0.1994529  0.4221218
 0.51475589 0.662121   1.         0.41675482 0.20095076 0.0621254
 0.03718635 0.04032236 0.04032236 0.04389651 0.0950852  0.12472334
 0.07094113 0.11622214 0.31367214 0.20095076 0.0621254  0.03718635
 0.04032236 0.04032236 0.04389651 0.0950852  0.12472334 0.07094113
 0.11622214 0.31367214 0.20095076 0.0621254  0.03718635 0.04032236
 0.04032236 0.04389651 0.0950852  0.12472334 0.07094113 0.11622214
 0.31367214 0.20095076 0.0621254  0.03718635 0.04032236 0.04032236
 0.04389651 0.0950852  0.12472334 0.07094113 0.11622214 0.31367214
 0.14822402 0.04784662 0.09623641 0.14899157 0.08142415 0.1821574
 0.12381678 0.04306542 0.10638021 0.06611166 0.14822402 0.04784662
 0.09623641 0.14899157 0.08142415 0.1821574  0.12381678 0.04306542
 0.10638021 0.06611166 0.12003247 0.13511365 0.09292429 0.10621866
 0.07483025 0.17737816 0.12003247 0.13511365 0.09292429 0.10621866
 0.07483025 0.17737816 0.12003247 0.13511365 0.09292429 0.10621866
 0.07483025 0.17737816 0.12003247 0.13511365 0.09292429 0.10621866
 0.07483025 0.17737816 0.12003247 0.13511365 0.09292429 0.10621866
 0.07483025 0.17737816 0.12003247 0.13511365 0.09292429 0.10621866
 0.07483025 0.17737816 0.09427187 0.11685547 0.09427187 0.19281611
 0.16443929 0.09427187 0.11685547 0.09427187 0.19281611 0.16443929
 0.09427187 0.11685547 0.09427187 0.19281611 0.16443929 0.09427187
 0.11685547 0.09427187 0.19281611 0.16443929 0.09427187 0.11685547
 0.09427187 0.19281611 0.16443929 0.09427187 0.11685547 0.09427187
 0.19281611 0.16443929 0.09427187 0.11685547 0.09427187 0.19281611
 0.16443929 0.09427187 0.11685547 0.09427187 0.19281611 0.16443929
 0.09427187 0.11685547 0.09427187 0.19281611 0.16443929 0.0884536
 0.20842753 0.13129333 0.1200645  0.2689542  0.0884536  0.20842753
 0.13129333 0.1200645  0.2689542  0.0884536  0.20842753 0.13129333
 0.1200645  0.2689542  0.0884536  0.20842753 0.13129333 0.1200645
 0.2689542  0.0884536  0.20842753 0.13129333 0.1200645  0.2689542
 0.0884536  0.20842753 0.13129333 0.1200645  0.2689542  0.0884536
 0.20842753 0.13129333 0.1200645  0.2689542  0.0884536  0.20842753
 0.13129333 0.1200645  0.2689542  0.1059123  0.0494256  0.10354376
 0.08658398 0.11555536 0.1059123  0.0494256  0.10354376 0.08658398
 0.11555536 0.1059123  0.0494256  0.10354376 0.08658398 0.11555536
 0.1059123  0.0494256  0.10354376 0.08658398 0.11555536 0.1059123
 0.0494256  0.10354376 0.08658398 0.11555536 0.1059123  0.0494256
 0.10354376 0.08658398 0.11555536 0.1059123  0.0494256  0.10354376
 0.08658398 0.11555536 0.1059123  0.0494256  0.10354376 0.08658398
 0.11555536 0.17572513 0.11046156 0.04433437 0.04011959 0.23630473
 0.16270052 0.17572513 0.11046156 0.04433437 0.04011959 0.23630473
 0.16270052 0.17572513 0.11046156 0.04433437 0.04011959 0.23630473
 0.16270052 0.17572513 0.11046156 0.04433437 0.04011959 0.23630473
 0.16270052 0.17572513 0.11046156 0.04433437 0.04011959 0.23630473
 0.16270052 0.04365818 0.08419829 0.04757165 0.0264464  0.12119248
 0.14096681 0.04365818 0.08419829 0.04757165 0.0264464  0.12119248
 0.14096681 0.04365818 0.08419829 0.04757165 0.0264464  0.12119248
 0.14096681 0.04365818 0.08419829 0.04757165 0.0264464  0.12119248
 0.14096681 0.10076046 0.11471524 0.22642425 0.12193554 0.18765322
 0.07723596 0.0892955  0.0892955  0.16955077 0.12810873 0.10829974
 0.1509616  0.16315034 0.08627322 0.10076046 0.11471524 0.22642425
 0.12193554 0.18765322 0.07723596 0.0892955  0.0892955  0.16955077
 0.12810873 0.10829974 0.1509616  0.16315034 0.08627322 0.10076046
 0.11471524 0.22642425 0.12193554 0.18765322 0.07723596 0.0892955
 0.0892955  0.16955077 0.12810873 0.10829974 0.1509616  0.16315034
 0.08627322 0.10076046 0.11471524 0.22642425 0.12193554 0.18765322
 0.07723596 0.0892955  0.0892955  0.16955077 0.12810873 0.10829974
 0.1509616  0.16315034 0.08627322 0.10076046 0.11471524 0.22642425
 0.12193554 0.18765322 0.07723596 0.0892955  0.0892955  0.16955077
 0.12810873 0.10829974 0.1509616  0.16315034 0.08627322 0.10076046
 0.11471524 0.22642425 0.12193554 0.18765322 0.07723596 0.0892955
 0.0892955  0.16955077 0.12810873 0.10829974 0.1509616  0.16315034
 0.08627322 0.06224881 0.14708787 0.09545973 0.11716463 0.16112236
 0.0381084  0.09545973 0.11716463 0.16112236 0.0381084  0.09545973
 0.11716463 0.16112236 0.0381084  0.06224881 0.14708787 0.09545973
 0.11716463 0.16112236 0.0381084  0.09545973 0.11716463 0.16112236
 0.0381084  0.09545973 0.11716463 0.16112236 0.0381084  0.15219489
 0.0433577  0.07115699 0.09480733 0.1316223  0.10574131 0.15219489
 0.0433577  0.07115699 0.09480733 0.1316223  0.10574131 0.15219489
 0.0433577  0.07115699 0.09480733 0.1316223  0.10574131 0.15219489
 0.0433577  0.07115699 0.09480733 0.1316223  0.10574131 0.17186242
 0.13233985 0.1714681  0.11139905 0.20652733 0.07936762 0.0914286
 0.11139905 0.20652733 0.11139905 0.20652733 0.11139905 0.20652733
 0.17186242 0.13233985 0.1714681  0.11139905 0.20652733 0.07936762
 0.0914286  0.11139905 0.20652733 0.11139905 0.20652733 0.11139905
 0.20652733 0.08846434 0.05680889 0.09761378 0.09041506 0.10584671
 0.08846434 0.05680889 0.09761378 0.09041506 0.10584671 0.08846434
 0.05680889 0.09761378 0.09041506 0.10584671 0.08846434 0.05680889
 0.09761378 0.09041506 0.10584671 0.08846434 0.05680889 0.09761378
 0.09041506 0.10584671 0.08846434 0.05680889 0.09761378 0.09041506
 0.10584671 0.08833172 0.0838153  0.08707273 0.05231925 0.08833172
 0.0838153  0.08707273 0.05231925 0.08833172 0.0838153  0.08707273
 0.05231925 0.08833172 0.0838153  0.08707273 0.05231925 0.08833172
 0.0838153  0.08707273 0.05231925 0.08833172 0.0838153  0.08707273
 0.05231925 0.08833172 0.0838153  0.08707273 0.05231925 0.08833172
 0.0838153  0.08707273 0.05231925 0.08833172 0.0838153  0.08707273
 0.05231925 0.08833172 0.0838153  0.08707273 0.05231925 0.26008758
 0.30369676 0.35752719 0.29583655 0.12488349 0.26083536 0.26008758
 0.30369676 0.35752719 0.29583655 0.12488349 0.26083536 0.26008758
 0.30369676 0.35752719 0.29583655 0.12488349 0.26083536 0.26008758
 0.30369676 0.35752719 0.29583655 0.12488349 0.26083536 0.26008758
 0.30369676 0.35752719 0.29583655 0.12488349 0.26083536 0.26008758
 0.30369676 0.35752719 0.29583655 0.12488349 0.26083536 0.26008758
 0.30369676 0.35752719 0.29583655 0.12488349 0.26083536 0.26008758
 0.30369676 0.35752719 0.29583655 0.12488349 0.26083536 0.10865513
 0.1762726  0.10347779 0.19892186 0.12412445 0.07833466 0.10284127
 0.10865513 0.1762726  0.10347779 0.10865513 0.1762726  0.10347779
 0.10865513 0.1762726  0.10347779 0.10865513 0.1762726  0.10347779
 0.10865513 0.1762726  0.10347779 0.10865513 0.1762726  0.10347779
 0.10865513 0.1762726  0.10347779 0.10865513 0.1762726  0.10347779
 0.10865513 0.1762726  0.10347779 0.10865513 0.1762726  0.10347779
 0.10865513 0.1762726  0.10347779 0.10865513 0.1762726  0.10347779
 0.10865513 0.1762726  0.10347779 0.10865513 0.1762726  0.10347779
 0.10865513 0.1762726  0.10347779 0.10865513 0.1762726  0.10347779
 0.15482023 0.10479658 0.16201032 0.06142427 0.05145031 0.15482023
 0.10479658 0.16201032 0.06142427 0.05145031 0.15482023 0.10479658
 0.16201032 0.06142427 0.05145031 0.15482023 0.10479658 0.16201032
 0.06142427 0.05145031 0.15482023 0.10479658 0.16201032 0.06142427
 0.05145031 0.14267681 0.0749866  0.06574014 0.14267681 0.0749866
 0.06574014 0.14267681 0.0749866  0.06574014 0.14267681 0.0749866
 0.06574014 0.14267681 0.0749866  0.06574014 0.14267681 0.0749866
 0.06574014 0.14267681 0.0749866  0.06574014 0.14267681 0.0749866
 0.06574014 0.14267681 0.0749866  0.06574014 0.14267681 0.0749866
 0.06574014 0.14947031 0.11687817 0.12153532 0.08262841 0.1009284
 0.08332432 0.1109843  0.11842843 0.12553125 0.05398496 0.3414907
 0.14947031 0.11687817 0.12153532 0.08262841 0.1009284  0.08332432
 0.1109843  0.11842843 0.12553125 0.05398496 0.3414907  0.14947031
 0.11687817 0.12153532 0.08262841 0.1009284  0.08332432 0.1109843
 0.11842843 0.12553125 0.05398496 0.3414907  0.11423885 0.05457436
 0.13246611 0.17506679 0.15155591 0.15500776 0.16320192 0.11423885
 0.05457436 0.13246611 0.17506679 0.15155591 0.15500776 0.16320192
 0.11423885 0.05457436 0.13246611 0.17506679 0.15155591 0.15500776
 0.16320192 0.11423885 0.05457436 0.13246611 0.17506679 0.15155591
 0.15500776 0.16320192 0.11423885 0.05457436 0.13246611 0.17506679
 0.15155591 0.15500776 0.16320192 0.11423885 0.05457436 0.13246611
 0.17506679 0.15155591 0.15500776 0.16320192 0.1320362  0.11234825
 0.15242939 0.11565348 0.21578142 0.1320362  0.11234825 0.15242939
 0.11565348 0.21578142 0.1320362  0.11234825 0.15242939 0.11565348
 0.21578142 0.1320362  0.11234825 0.15242939 0.11565348 0.21578142
 0.1320362  0.11234825 0.15242939 0.11565348 0.21578142 0.1320362
 0.11234825 0.15242939 0.11565348 0.21578142 0.1320362  0.11234825
 0.15242939 0.11565348 0.21578142 0.1320362  0.11234825 0.15242939
 0.11565348 0.21578142 0.21488991 0.15139216 0.16275054 0.13811135

- Final Custom function

In [59]:
def recommend(category):
    #Based on given predicted job category id getting the index of that job category in my dataset 
    index = df2[df2['Encoded_Category'] == category].index[0] 

    #Based on the fetched index getting the similarity score list of that job
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1]) 
    # print(distances) # For testing purpose
    
    unique_set = set([])
    similarity_score = []
    
    for i in distances[0:100]: 
        if len(unique_set) < 5:
            job = df2.iloc[i[0]].Category
            score = "{:.2f}".format(i[1])
            if job not in unique_set and score != "1.00":
                unique_set.add(job)
                similarity_score.append(i[1])
                print(f"{job}, {score}") # Print each unique value and its corresponding similarity score
        else:
            break

In [60]:
print(category_mapping.get(0))
recommend(0)

Advocate
Civil Engineer, 0.42
Advocate, 0.33
Health and fitness, 0.28
Business Analyst, 0.19
Database, 0.17

In [65]:
print(category_mapping.get(15))
recommend(15)

Java Developer
Java Developer, 0.55
HR, 0.36
Automation Testing, 0.27
Blockchain, 0.23
DotNet Developer, 0.21

In [66]:
print(category_mapping.get(18))
recommend(18)

Operations Manager
Operations Manager, 0.53
PMO, 0.52
DevOps Engineer, 0.48
Business Analyst, 0.40
HR, 0.34